#!/usr/local/bin/perl -w
# Copyright (c) 2000-2008 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    "cons",
    "build",
    "platform",
    "buildType",
    "buildFlavour",
    "mozBin",
);

$cons->Install($mozBin, "updater.ini");

if ($platform eq "darwin") {
    # On Mac OS X, the updater.ini must also go into the updater.app directory,
    # see bug 85523.
    $cons->Install($mozBin . "/updater.app/Contents/MacOS", "updater.ini");
}
