#!/usr/local/bin/perl -w
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

Import(
    "cons",
    "platform",
    "supportDir",
    "build"
);

local $build = substr($build, 1, length($build)); # drop the leading '#'
my ($exeName, $make, $makefile);
if ($platform eq "win") {
    $exeName = "bin\\tidy.exe";
    $make = "nmake";
    $makefile = "Makefile.vc6";
    $tidyDir = "$build\\tidy\\build\\msvc\\";
} else {
    $exeName = "bin/tidy";
    if ($platform eq "darwin") {
      $make = "RANLIB=ranlib make";
    } else {
      $make = "make";
    }
    $makefile = "Makefile";
    $tidyDir = "$build/tidy/build/gmake";
}


%consLocal = $cons->copy();
$consLocal{CPPPATH} = "include";
$consLocal{LIBPATH} = "obj";
$consLocal = new cons(%consLocal);

$consLocal->Command($exeName, 
                    "build/gmake/Makefile",
                    "build/msvc/Makefile.vc6",
                    "console/tab2space.c",
                    "console/tidy.c",
                    "include/buffio.h",
                    "include/fileio.h",
                    "include/platform.h",
                    "include/tidy.h",
                    "include/tidyenum.h",
                    "src/access.c",
                    "src/access.h",
                    "src/alloc.c",
                    "src/attrask.c",
                    "src/attrdict.c",
                    "src/attrdict.h",
                    "src/attrget.c",
                    "src/attrs.c",
                    "src/attrs.h",
                    "src/buffio.c",
                    "src/charsets.c",
                    "src/charsets.h",
                    "src/clean.c",
                    "src/clean.h",
                    "src/config.c",
                    "src/config.h",
                    "src/entities.c",
                    "src/entities.h",
                    "src/fileio.c",
                    "src/forward.h",
                    "src/iconvtc.c",
                    "src/iconvtc.h",
                    "src/istack.c",
                    "src/lexer.c",
                    "src/lexer.h",
                    "src/localize.c",
                    "src/message.h",
                    "src/parser.c",
                    "src/parser.h",
                    "src/pprint.c",
                    "src/pprint.h",
                    "src/streamio.c",
                    "src/streamio.h",
                    "src/tagask.c",
                    "src/tags.c",
                    "src/tags.h",
                    "src/tidy-int.h",
                    "src/tidylib.c",
                    "src/tmbstr.c",
                    "src/tmbstr.h",
                    "src/utf8.c",
                    "src/utf8.h",
                    "src/win32tc.c",
                    "src/win32tc.h",
                    "obj/empty.txt",
                    qq{cd $tidyDir && $make -f $makefile}
                   );
$consLocal->Install("$supportDir/html", $exeName);

