# Komodo XBL language service.
#
# Generated by 'luddite.py' on Fri Oct 20 08:47:11 2006.
#

import logging
from koXMLLanguageBase import koXMLLanguageBase


log = logging.getLogger("koXBLLanguage")
#log.setLevel(logging.DEBUG)


def registerLanguage(registry):
    log.debug("Registering language XBL")
    registry.registerLanguage(KoXBLLanguage())


class KoXBLLanguage(koXMLLanguageBase):
    name = "XBL"
    lexresLangName = "XBL"
    _reg_desc_ = "%s Language" % name
    _reg_contractid_ = "@activestate.com/koLanguage?language=%s;1" % name
    _reg_clsid_ = "{46D9A883-9410-47D2-B4CE-5D3186A6D4C8}"
    defaultExtension = '.xbl'

    lang_from_udl_family = {'CSL': 'JavaScript', 'M': 'XML'}

    publicIdList = ["-//MOZILLA//DTD XBL V1.0//EN"]
    systemIdList = ["http://www.mozilla.org/xbl"]
    namespaces = ["http://www.mozilla.org/xbl"]

    searchURL = "http://www.google.com/search?q=site%3Ahttp%3A%2F%2Fdeveloper.mozilla.org%2Fen%2Fdocs%2FXBL%3AXBL_1.0_Reference+%W"
