#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'platform',
    'supportDir',
    'build',
    'mozChromeDir',
    'productType',
);

$cons->Install("$supportDir/images", 'newline.gif');

$cons->InstallInChrome('icon-community.png');
$cons->InstallInChrome('icon-mailing-list.png');
$cons->InstallInChrome('icon-bugs.png');
$cons->InstallInChrome('webServicesImg.png');
$cons->InstallInChrome('browser_buttons.gif');
$cons->InstallInChrome('small-x.png');
$cons->InstallInChrome('small-x_hover.png');
$cons->InstallInChrome('small-x_disable.png');
$cons->InstallInChrome('small-arrow.png');
$cons->InstallInChrome('small-arrow_hover.png');
$cons->InstallInChrome('small-arrow_disable.png');
$cons->InstallInChrome('small-arrow-up.png');
$cons->InstallInChrome('small-arrow-up_hover.png');
$cons->InstallInChrome('small-arrow-up_disable.png');

$cons->InstallInChrome('komodo-icon.png');

$cons->InstallInChrome('go.png');
$cons->InstallInChrome('go-hover.png');

$cons->InstallInChrome('leftarrow.png');
$cons->InstallInChrome('rightarrow.png');
$cons->InstallInChrome('watch.png');
$cons->InstallInChrome('watch_hover.png');
$cons->InstallInChrome('watch_disable.png');

$cons->InstallInChrome('menu-arrow-up.gif');
$cons->InstallInChrome('menu-arrow-down.gif');
$cons->InstallInChrome('menu-arrow-left.gif');
$cons->InstallInChrome('menu-arrow-right.gif');

$cons->InstallInChrome('boldButton.png');
$cons->InstallInChrome('boldButton_hover.png');
$cons->InstallInChrome('boldButton_disable.png');
$cons->InstallInChrome('italicButton.png');
$cons->InstallInChrome('italicButton_hover.png');
$cons->InstallInChrome('italicButton_disable.png');
$cons->InstallInChrome('colorbg.png');
$cons->InstallInChrome('smallheader-bg.png');

$cons->InstallInChrome('arrow_right_6x3.png');

$cons->InstallInChrome('scrollArrowRight-mini.png');
$cons->InstallInChrome('scrollArrowRight.png');
$cons->InstallInChrome('scrollArrowRight_hover.png');
$cons->InstallInChrome('scrollArrowRight_disable.png');
$cons->InstallInChrome('scrollArrowLeft.png');
$cons->InstallInChrome('scrollArrowLeft_hover.png');
$cons->InstallInChrome('scrollArrowLeft_disable.png');

$cons->InstallInChrome('icon_check_inprogress.png');
$cons->InstallInChrome('icon_check_ok.png');
$cons->InstallInChrome('icon_check_error.png');
$cons->InstallInChrome('icon_check_warning.png');
$cons->InstallInChrome('icon_check_off.png');

$cons->InstallInChrome('twisty-closed.gif');
$cons->InstallInChrome('twisty-open.gif');

$cons->InstallInChrome('folder-closed.png');
$cons->InstallInChrome('folder-open.png');
$cons->InstallInChrome('folder-closed-pink.png');
$cons->InstallInChrome('folder-open-pink.png');
$cons->InstallInChrome('folder-closed-blue.png');
$cons->InstallInChrome('folder-open-blue.png');

$cons->InstallInChrome('newTemplate.png');
$cons->InstallInChrome('run_commands.png');
$cons->InstallInChrome('run_commands_missing.png');
$cons->InstallInChrome('xlink.png');
$cons->InstallInChrome('snippet.png');
$cons->InstallInChrome('open_shortcut.png');

$cons->InstallInChrome('file_icon_missing.png');
$cons->InstallInChrome('file_icon_readonly.png');
$cons->InstallInChrome('file_icon_readonly_ok.png');
$cons->InstallInChrome('file_icon_readonly_sync.png');
$cons->InstallInChrome('file_icon_readonly_conflict.png');
$cons->InstallInChrome('file_icon_readonly_add.png');
$cons->InstallInChrome('file_icon_readonly_delete.png');
$cons->InstallInChrome('file_icon.png');
$cons->InstallInChrome('file_icon_ok.png');
$cons->InstallInChrome('file_icon_sync.png');
$cons->InstallInChrome('file_icon_conflict.png');
$cons->InstallInChrome('file_icon_add.png');
$cons->InstallInChrome('file_icon_delete.png');
$cons->InstallInChrome('file_icon_edit.png');
$cons->InstallInChrome('file_icon_edit_ok.png');
$cons->InstallInChrome('file_icon_edit_sync.png');
$cons->InstallInChrome('file_icon_edit_conflict.png');

$cons->InstallInChrome('project_icon_readonly.png');
$cons->InstallInChrome('project_icon_readonly_ok.png');
$cons->InstallInChrome('project_icon_readonly_sync.png');
$cons->InstallInChrome('project_icon_readonly_conflict.png');
$cons->InstallInChrome('project_icon.png');
$cons->InstallInChrome('project_icon_ok.png');
$cons->InstallInChrome('project_icon_sync.png');
$cons->InstallInChrome('project_icon_conflict.png');
$cons->InstallInChrome('project_icon_add.png');
$cons->InstallInChrome('project_icon_delete.png');
$cons->InstallInChrome('project_icon_edit.png');
$cons->InstallInChrome('project_icon_edit_ok.png');
$cons->InstallInChrome('project_icon_edit_sync.png');
$cons->InstallInChrome('project_icon_edit_conflict.png');

$cons->InstallInChrome('more.gif');
$cons->InstallInChrome('less.gif');

$cons->InstallInChrome('tab_icon_blank.png');
$cons->InstallInChrome('tab_icon_readonly.png');
$cons->InstallInChrome('tab_icon_readonly_ok.png');
$cons->InstallInChrome('tab_icon_readonly_sync.png');
$cons->InstallInChrome('tab_icon_readonly_conflict.png');
$cons->InstallInChrome('tab_icon_ok.png');
$cons->InstallInChrome('tab_icon_sync.png');
$cons->InstallInChrome('tab_icon_conflict.png');
$cons->InstallInChrome('tab_icon_edit.png');
$cons->InstallInChrome('tab_icon_add.png');
$cons->InstallInChrome('tab_icon_delete.png');

$cons->InstallInChrome('bulletlist.png');
$cons->InstallInChrome('bulletlist_disable.png');
$cons->InstallInChrome('bulletlist_hover.png');

# seperate tab status icons for the new status tab widget
$cons->InstallInChrome('status_icon_delete.png');
$cons->InstallInChrome('status_icon_edit.png');
$cons->InstallInChrome('status_icon_add.png');
$cons->InstallInChrome('status_icon_sync.png');
$cons->InstallInChrome('status_icon_ok.png');
$cons->InstallInChrome('status_icon_conflict.png');
$cons->InstallInChrome('status_icon_readonly.png');

$cons->InstallInChrome('new_toolboxitem_icon.png');
$cons->InstallInChrome('new_toolboxitem_disabled.png');
$cons->InstallInChrome('new_toolboxitem_hover.png');
$cons->InstallInChrome('new_project_icon.png');

$cons->InstallInChrome('tab_picker_hover.png');
$cons->InstallInChrome('tab_picker.png');

$cons->InstallInChrome('small_lock.png');

$cons->InstallInChrome('menu_icon.png');
$cons->InstallInChrome('toolbar_icon.png');


$cons->InstallInChrome('prompt.xpm');
$cons->InstallInChrome('prompt_stdin.xpm');

$cons->InstallInChrome("transparent_white.png");

# new seperate images for Add Item toolbars
$cons->InstallInChrome('new_custom_menu.png');
$cons->InstallInChrome('new_custom_toolbar.png');
$cons->InstallInChrome('new_dialog.png');
$cons->InstallInChrome('new_file.png');
$cons->InstallInChrome('existing_file.png');
$cons->InstallInChrome('new_folder.png');
$cons->InstallInChrome('new_live_folder.png');
$cons->InstallInChrome('new_macro.png');
$cons->InstallInChrome('new_open_shortcut.png');
$cons->InstallInChrome('new_project.png');
$cons->InstallInChrome('new_project_hover.png');
$cons->InstallInChrome('remote_file.png');
$cons->InstallInChrome('new_run_command.png');
$cons->InstallInChrome('new_snippet.png');
$cons->InstallInChrome('new_template.png');
$cons->InstallInChrome('new_url.png');

$cons->InstallInChrome('open_project.png');
$cons->InstallInChrome('open_project_hover.png');


# Two checkbox icons from mozilla/themes/classic/global/win/checkbox.
# Needed for <treecol type="checkbox"> usage. On all plats *except
# Mac OS X we could use these images as
# "chrome://global/skin/checkbox/cbox-check.gif", but because of OS X
# we've pulled them into Komodo's skin.
$cons->InstallInChrome('cbox-check.gif');
$cons->InstallInChrome('cbox-check-dis.gif');

