#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'mozBin',
    'unsiloedPythonExe',
    'jarring',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'mozVersion',
);

$cons->InstallAs("$mozBin/chrome/iconsets/classic/chrome.manifest",
                 "classic/chrome.manifest");