#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'build',
    'platform',
    'productType',
    'buildFlavour',
    'buildType',
    'unsiloedPythonExe',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'supportDir',
    'komodoPythonUtilsDir',
    'mozVersion',
    'sdkDir',
    'mozSrc',
);

$cons->InstallPythonUtility('styles.py');
$cons->Preprocess('factoryStyleSettings.p.py',
                  'factoryStyleSettings.py');
$cons->InstallPythonUtility('factoryStyleSettings.py');
$cons->InstallPythonUtility('schemebase.py');
$cons->InstallPythonUtility('userStyleSettings.py');
$cons->Install($idlExportDir, 'koIScintillaSchemeService.idl');
$cons->BuildAndInstallXpt('koIScintillaSchemeService.idl');
$cons->Preprocess('koScintillaSchemeService.p.py',
                  'koScintillaSchemeService.py');
$cons->InstallXpcomComponent('koScintillaSchemeService.py');

$cons->InstallAs("$supportDir/schemes/3024_Dark.ksf", 'color_schemes/base16-3024-dark.ksf');
$cons->InstallAs("$supportDir/schemes/3024_Light.ksf", 'color_schemes/base16-3024-light.ksf');
$cons->InstallAs("$supportDir/schemes/Ashes_Dark.ksf", 'color_schemes/base16-ashes-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Ashes_Light.ksf", 'color_schemes/base16-ashes-light.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierdune_Dark.ksf", 'color_schemes/base16-atelierdune-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierdune_Light.ksf", 'color_schemes/base16-atelierdune-light.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierforest_Dark.ksf", 'color_schemes/base16-atelierforest-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierforest_Light.ksf", 'color_schemes/base16-atelierforest-light.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierheath_Dark.ksf", 'color_schemes/base16-atelierheath-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierheath_Light.ksf", 'color_schemes/base16-atelierheath-light.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierlakeside_Dark.ksf", 'color_schemes/base16-atelierlakeside-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierlakeside_Light.ksf", 'color_schemes/base16-atelierlakeside-light.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierseaside_Dark.ksf", 'color_schemes/base16-atelierseaside-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Atelierseaside_Light.ksf", 'color_schemes/base16-atelierseaside-light.ksf');
$cons->InstallAs("$supportDir/schemes/Bespin_Dark.ksf", 'color_schemes/base16-bespin-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Bespin_Light.ksf", 'color_schemes/base16-bespin-light.ksf');
$cons->InstallAs("$supportDir/schemes/Brewer_Dark.ksf", 'color_schemes/base16-brewer-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Brewer_Light.ksf", 'color_schemes/base16-brewer-light.ksf');
$cons->InstallAs("$supportDir/schemes/Chalk_Dark.ksf", 'color_schemes/base16-chalk-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Chalk_Light.ksf", 'color_schemes/base16-chalk-light.ksf');
$cons->InstallAs("$supportDir/schemes/Codeschool_Dark.ksf", 'color_schemes/base16-codeschool-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Codeschool_Light.ksf", 'color_schemes/base16-codeschool-light.ksf');
$cons->InstallAs("$supportDir/schemes/Default_Dark.ksf", 'color_schemes/base16-default-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Default_Light.ksf", 'color_schemes/base16-default-light.ksf');
$cons->InstallAs("$supportDir/schemes/Eighties_Dark.ksf", 'color_schemes/base16-eighties-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Eighties_Light.ksf", 'color_schemes/base16-eighties-light.ksf');
$cons->InstallAs("$supportDir/schemes/Embers_Dark.ksf", 'color_schemes/base16-embers-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Embers_Light.ksf", 'color_schemes/base16-embers-light.ksf');
$cons->InstallAs("$supportDir/schemes/Google_Dark.ksf", 'color_schemes/base16-google-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Google_Light.ksf", 'color_schemes/base16-google-light.ksf');
$cons->InstallAs("$supportDir/schemes/Grayscale_Dark.ksf", 'color_schemes/base16-grayscale-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Grayscale_Light.ksf", 'color_schemes/base16-grayscale-light.ksf');
$cons->InstallAs("$supportDir/schemes/Greenscreen_Dark.ksf", 'color_schemes/base16-greenscreen-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Greenscreen_Light.ksf", 'color_schemes/base16-greenscreen-light.ksf');
$cons->InstallAs("$supportDir/schemes/Isotope_Dark.ksf", 'color_schemes/base16-isotope-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Isotope_Light.ksf", 'color_schemes/base16-isotope-light.ksf');
$cons->InstallAs("$supportDir/schemes/Londontube_Dark.ksf", 'color_schemes/base16-londontube-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Londontube_Light.ksf", 'color_schemes/base16-londontube-light.ksf');
$cons->InstallAs("$supportDir/schemes/Marrakesh_Dark.ksf", 'color_schemes/base16-marrakesh-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Marrakesh_Light.ksf", 'color_schemes/base16-marrakesh-light.ksf');
$cons->InstallAs("$supportDir/schemes/Mocha_Dark.ksf", 'color_schemes/base16-mocha-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Mocha_Light.ksf", 'color_schemes/base16-mocha-light.ksf');
$cons->InstallAs("$supportDir/schemes/Monokai_Dark.ksf", 'color_schemes/base16-monokai-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Monokai_Light.ksf", 'color_schemes/base16-monokai-light.ksf');
$cons->InstallAs("$supportDir/schemes/Ocean_Dark.ksf", 'color_schemes/base16-ocean-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Ocean_Light.ksf", 'color_schemes/base16-ocean-light.ksf');
$cons->InstallAs("$supportDir/schemes/Paraiso_Dark.ksf", 'color_schemes/base16-paraiso-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Paraiso_Light.ksf", 'color_schemes/base16-paraiso-light.ksf');
$cons->InstallAs("$supportDir/schemes/Railscasts_Dark.ksf", 'color_schemes/base16-railscasts-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Railscasts_Light.ksf", 'color_schemes/base16-railscasts-light.ksf');
$cons->InstallAs("$supportDir/schemes/Shapeshifter_Dark.ksf", 'color_schemes/base16-shapeshifter-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Shapeshifter_Light.ksf", 'color_schemes/base16-shapeshifter-light.ksf');
$cons->InstallAs("$supportDir/schemes/Solarized_Dark.ksf", 'color_schemes/base16-solarized-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Solarized_Light.ksf", 'color_schemes/base16-solarized-light.ksf');
$cons->InstallAs("$supportDir/schemes/Tomorrow_Dark.ksf", 'color_schemes/base16-tomorrow-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Tomorrow_Light.ksf", 'color_schemes/base16-tomorrow-light.ksf');
$cons->InstallAs("$supportDir/schemes/Twilight_Dark.ksf", 'color_schemes/base16-twilight-dark.ksf');
$cons->InstallAs("$supportDir/schemes/Twilight_Light.ksf", 'color_schemes/base16-twilight-light.ksf');

$cons->BuildAndInstallXpt('koIKeybindingSchemeService.idl');
$cons->InstallXpcomComponent('koKeybindingSchemeService.py');
if ($platform eq "darwin") {
    $cons->Preprocess('Default.p.kkf', 'Windows.kkf');
    $cons->Install("$supportDir/schemes", 'Windows.kkf');
    $cons->Preprocess('Mac.p.kkf', 'Default.kkf');
    $cons->Install("$supportDir/schemes", 'Default.kkf');
} else {
    $cons->Preprocess('Default.p.kkf', 'Default.kkf');
    $cons->Install("$supportDir/schemes", 'Default.kkf');
}
$cons->Preprocess('Emacs.p.kkf', 'Emacs.kkf');
$cons->Install("$supportDir/schemes", 'Emacs.kkf');

$cons->BuildAndInstallXpt('koIViCommandDetail.idl');
$cons->InstallXpcomComponent('koViCommandDetail.py');

$cons->Preprocess("_vi.p.kkf", "_vi.kkf");
$cons->Install("$supportDir/schemes", '_vi.kkf');
$cons->Depends("_vi.kkf", "Default.kkf");

$cons->Preprocess("Vi.p.kkf", "Vi.kkf");
$cons->Install("$supportDir/schemes", 'Vi.kkf');
$cons->Depends("Vi.kkf", "_vi.kkf");
