#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'build',
    'platform',
    'productType',
    'buildFlavour',
    'buildType',
    'unsiloedPythonExe',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'supportDir',
    'komodoPythonUtilsDir',
    'mozVersion',
    'sdkDir',
);

$cons->InstallPythonUtility('styles.py');
$cons->Preprocess('factoryStyleSettings.unprocessed.py',
                  'factoryStyleSettings.py');
$cons->InstallPythonUtility('factoryStyleSettings.py');
$cons->InstallPythonUtility('userStyleSettings.py');
$cons->Install($idlExportDir, 'koIScintillaSchemeService.idl');
$cons->BuildAndInstallXpt('koIScintillaSchemeService.idl');
$cons->Preprocess('koScintillaSchemeService.unprocessed.py',
                  'koScintillaSchemeService.py');
$cons->InstallXpcomComponent('koScintillaSchemeService.py');
$cons->Preprocess('Default.unprocessed.ksf', 'Default.ksf');
$cons->Install("$supportDir/schemes", 'Default.ksf');
$cons->Preprocess('Dark.unprocessed.ksf', 'Dark.ksf');
$cons->Install("$supportDir/schemes", 'Dark.ksf');
$cons->Preprocess('Medium.unprocessed.ksf', 'Medium.ksf');
$cons->Install("$supportDir/schemes", 'Medium.ksf');
$cons->Preprocess('Bright.unprocessed.ksf', 'Bright.ksf');
$cons->Install("$supportDir/schemes", 'Bright.ksf');

$cons->BuildAndInstallXpt('koIKeybindingSchemeService.idl');
$cons->InstallXpcomComponent('koKeybindingSchemeService.py');
if ($platform eq "darwin") {
    $cons->Preprocess('Default.unprocessed.kkf', 'Windows.kkf');
    $cons->Install("$supportDir/schemes", 'Windows.kkf');
    $cons->Preprocess('Mac.unprocessed.kkf', 'Default.kkf');
    $cons->Install("$supportDir/schemes", 'Default.kkf');
} else {
    $cons->Preprocess('Default.unprocessed.kkf', 'Default.kkf');
    $cons->Install("$supportDir/schemes", 'Default.kkf');
}
$cons->Preprocess('Emacs.unprocessed.kkf', 'Emacs.kkf');
$cons->Install("$supportDir/schemes", 'Emacs.kkf');

$cons->BuildAndInstallXpt('koIViCommandDetail.idl');
$cons->InstallXpcomComponent('koViCommandDetail.py');

$cons->Preprocess("_vi.p.kkf", "_vi.kkf");
$cons->Install("$supportDir/schemes", '_vi.kkf');
$cons->Depends("_vi.kkf", "Default.kkf");

$cons->Preprocess("Vi.p.kkf", "Vi.kkf");
$cons->Install("$supportDir/schemes", 'Vi.kkf');
$cons->Depends("Vi.kkf", "_vi.kkf");
