#!/usr/local/bin/perl
# Copyright (c) 2009 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'buildFlavour',
    'sdkDir',
    'build',
    'mozBin',
    'unsiloedPythonExe',
);


$cons->KoExt("koinstall");

# For quick development, comment out the "KoExt" call above and 
# use this:
#$cons->KoExtSourceDevInstall();

