#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import('cons', 'mozChromeDir');

$cons->InstallInChrome('folder.png');
$cons->InstallInChrome('newDirectory.png');
$cons->InstallInChrome('openFolder.png');
$cons->InstallInChrome('upLevel.png');
$cons->InstallInChrome('upLevel_disable.png');

$cons->InstallInChrome('refresh.png');
$cons->InstallInChrome('warning_small.png');
$cons->InstallInChrome('configure.gif');

$cons->InstallInChrome('goBack.png');
$cons->InstallInChrome('goBack_hover.png');
$cons->InstallInChrome('goBack_disable.png');
$cons->InstallInChrome('preview.png');
$cons->InstallInChrome('preview_hover.png');
$cons->InstallInChrome('preview_disable.png');
$cons->InstallInChrome('refreshFile.png');
$cons->InstallInChrome('serverAccount.png');
