# Komodo MXML language service.
#
# Generated by 'luddite.py' on Thu Mar 15 16:06:49 2007.
#

import logging
from koXMLLanguageBase import koXMLLanguageBase


log = logging.getLogger("koMXMLLanguage")
#log.setLevel(logging.DEBUG)


def registerLanguage(registry):
    log.debug("Registering language MXML")
    registry.registerLanguage(KoMXMLLanguage())


class KoMXMLLanguage(koXMLLanguageBase):
    name = "MXML"
    lexresLangName = "MXML"
    _reg_desc_ = "%s Language" % name
    _reg_contractid_ = "@activestate.com/koLanguage?language=%s;1" % name
    _reg_clsid_ = "{8cdb154f-47e6-420e-a918-1548ab748499}"
    defaultExtension = '.mxml'

    lang_from_udl_family = {'CSL': 'ActionScript', 'M': 'XML'}

    systemIdList = ["http://www.adobe.com/2006/mxml",
                  "http://www.macromedia.com/2003/mxml"]
    namespaces = ["http://www.adobe.com/2006/mxml",
                  "http://www.macromedia.com/2003/mxml"]
