#!/usr/local/bin/perl
# Copyright (c) 2003-2011 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    'supportDir',
);


$cons->Install("$supportDir/lint/javascript", "lintWrapper.js");
