#!/usr/local/bin/perl
# Copyright (c) 2007 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    "cons",
    "komodoPythonUtilsDir",
    "ranRegxpcomStateFileName",
    "platform",
    "buildType",
    "buildFlavour",
);

$cons->InstallRecursive("$komodoPythonUtilsDir/koWndWrapper",
			cwd() . "/src/python-sitelib/koWndWrapper",
			('\.svn'));
