#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'mozBin',
    'unsiloedPythonExe',
    'jarring',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'mozVersion',
    'withHTTPInspector',
    'withSCC',
    'withSleuth',
    'withDebugging',
);

$cons->InstallAs("$mozBin/chrome/skin/gnome/Ambiance/chrome.manifest",
                 "Ambiance/chrome.manifest");