#!/usr/local/bin/perl -w
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

use Cwd;

Import(
    "cons",
    "mozBin",
    "platform",
    "build",
    "install",
    "komodoPythonUtilsDir",
    "productType",
    "version",
    'scintillaBuildDir',
);

my $LIB = '.a';
my $mkwriteable = "chmod u+w";
if ($platform eq "win") {
    $LIB = '.lib';
    $mkwriteable = "attrib -R";
}


my $landmark = "$komodoPythonUtilsDir/SilverCity/__init__.py";
$cons->Command(
    $landmark,
    "setup.py",
    # Actually we depends on most everything under:
    #   ../scintilla/include/...
    #   ../scintilla/src/...
    # but depending on these two generated files should do the trick.
    "../scintilla/include/Scintilla.h",
    "../scintilla/include/Scintilla.iface",
    
    "libpcre$LIB", # built and installed from contrib/pcre
    
    #XXX '--prefix' necessary for 'setup.py install' because
    #    '--install-data' handling is broken: the 'default.css' data
    #    file still gets installed to the calling Python's site-packages
    #    dir.
    qq(
        cd %1:d && $mkwriteable PySilverCity/SilverCity/ScintillaConstants.py
        cd %1:d && python PySilverCity/Src/write_scintilla.py ../scintilla/include ../scintilla/include/Scintilla.iface PySilverCity/SilverCity/ScintillaConstants.py
        cd %1:d && python setup.py build
        cd %1:d && python setup.py install --install-lib=$komodoPythonUtilsDir --install-scripts=bitbucket --install-data=bitbucket --prefix=bitbucket
    )
);

my $pluginName;

if ($platform eq "win") {
    # no depends?
} elsif ($platform eq "darwin") {
    $cons->Depends($landmark, "$mozBin/libscintilla.dylib");
} else {
    $cons->Depends($landmark, "$mozBin/libscintilla.so");
}
$cons->DependsRecursive($landmark, "PySilverCity", ('\.svn'));
$cons->DependsRecursive($landmark, "Lib", ('\.svn'));
$cons->DependsRecursive($landmark, "CSS", ('\.svn'));

