[
    object,
    uuid([[%guid]]),
    dual,
    helpstring("Insert your help here"),
    pointer_default(unique)
]

interface [[%tabstop:IMyInterface]] : IDispatch
{
    [[%tabstop:// Insert your methods here]]
};

