#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'mozChromeDir',
    'platform',
    'productType',
    'buildFlavour',
    'unsiloedPythonExe',
    'mozVersion',
);

$cons->InstallInChrome('scrolltabs.xml');
$cons->InstallInChrome('buttons.xml');
$cons->InstallInChrome('listbox.xml');
$cons->InstallInChrome('colorpicker.xml');
$cons->Preprocess('scintilla.p.xml', 'scintilla.xml');
$cons->InstallInChrome('scintilla.xml');
$cons->Preprocess('scintilla-overlay.p.xul', 'scintilla-overlay.xul');
$cons->InstallInChrome('scintilla-overlay.xul');
$cons->InstallInChrome('text-link.xml');
$cons->InstallInChrome('widgets.xml');
$cons->Preprocess('views.p.xml', 'views.xml');
$cons->InstallInChrome('views.xml');
$cons->InstallInChrome('views-tabbed.xml');
$cons->InstallInChrome('views-browser.xml');
$cons->InstallInChrome('views-xul.xml');
$cons->Preprocess('views-editor.p.xml', 'views-editor.xml');
$cons->InstallInChrome('views-editor.xml');
$cons->Preprocess('views-buffer.p.xml', 'views-buffer.xml');
$cons->InstallInChrome('views-buffer.xml');
$cons->Preprocess('views-diff.p.xml', 'views-diff.xml');
$cons->InstallInChrome('views-diff.xml');
$cons->InstallInChrome('views-multi.xml');
$cons->Preprocess('views-terminal.p.xml', 'views-terminal.xml');
$cons->InstallInChrome('views-terminal.xml');
$cons->Preprocess('views-minimap.p.xml', 'views-minimap.xml');
$cons->InstallInChrome('views-minimap.xml');
$cons->InstallInChrome('pane.xml');
$cons->InstallInChrome('toolbar.xml');
