#!/usr/local/bin/perl

# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

# Conscript for building the scintilla dll (with lexer)
#   Neil Hodgson provides a makefile to build this so we are no going to
#   duplicate that, however, to ensure rebuilding as necessary the
#   Command that call the makefile should have the proper dependencies
#   (i.e. inputs). In fact, to work with the build->src link they *must* all
#   be listed (this is a good thing). These will have to be kept in sync.

Import(
    'cons',
    'buildType',
    'mozBin',
    'unsiloedPythonExe',
    'ranRegxpcomStateFileName',
);

# this is what we want from the scintilla build process
$pluginName = '../bin/SciLexer.dll';

%consLocal = $cons->copy();
my $LDFLAGS = $consLocal{'LDFLAGS'};

$cons->Command(
    [$pluginName],              # %0
    "scintilla_vc6.mak",        # %1
    "../include/HFacer.py",     # %2
    "../include/Face.py",
    "../include/Accessor.h",
    "../include/KeyWords.h",
    "../include/Platform.h",
    "../include/PropSet.h",
    "../include/SciLexer.h",
    "../include/Scintilla.h",
    "../include/Scintilla.iface",
    "../include/ScintillaWidget.h",
    "../include/SString.h",
    "../include/WindowAccessor.h",
    "../src/AutoComplete.cxx",
    "../src/AutoComplete.h",
    "../src/CallTip.cxx",
    "../src/CallTip.h",
    "../src/CellBuffer.cxx",
    "../src/CellBuffer.h",
    "../src/CharacterSet.h",
    "../src/CharClassify.cxx",
    "../src/CharClassify.h",
    "../src/ContractionState.cxx",
    "../src/ContractionState.h",
    "../src/Decoration.cxx",
    "../src/Decoration.h",
    "../src/Document.cxx",
    "../src/Document.h",
    "../src/DocumentAccessor.cxx",
    "../src/DocumentAccessor.h",
    "../src/Editor.cxx",
    "../src/Editor.h",
    "../src/ExternalLexer.cxx",
    "../src/ExternalLexer.h",
    "../src/FontQuality.h",
    "../src/Indicator.cxx",
    "../src/Indicator.h",
    "../src/KeyMap.cxx",
    "../src/KeyMap.h",
    "../src/KeyWords.cxx",
    "../src/LineMarker.cxx",
    "../src/LineMarker.h",
    "../src/LexAbaqus.cxx",
    "../src/LexASY.cxx",
    "../src/LexADA.cxx",
    "../src/LexAPDL.cxx",
    "../src/LexAsm.cxx",
    "../src/LexAsn1.cxx",
    "../src/LexAU3.cxx",
    "../src/LexAVE.cxx",
    "../src/LexBaan.cxx",
    "../src/LexBash.cxx",
    "../src/LexBasic.cxx",
    "../src/LexBullant.cxx",
    "../src/LexCaml.cxx",
    "../src/LexCLW.cxx",
    "../src/LexCmake.cxx",
    "../src/LexCOBOL.cxx",
    "../src/LexConf.cxx",
    "../src/LexCPP.cxx",
    "../src/LexCrontab.cxx",
    "../src/LexCsound.cxx",
    "../src/LexCSS.cxx",
    "../src/LexD.cxx",
    "../src/LexEiffel.cxx",
    "../src/LexErlang.cxx",
    "../src/LexEScript.cxx",
    "../src/LexFlagship.cxx",
    "../src/LexForth.cxx",
    "../src/LexFortran.cxx",
    "../src/LexGAP.cxx",
    "../src/LexGen.py",
    "../src/LexGui4Cli.cxx",
    "../src/LexHaskell.cxx",
    "../src/LexHTML.cxx",
    "../src/LexInno.cxx",
    "../src/LexKix.cxx",
    "../src/LexLisp.cxx",
    "../src/LexLout.cxx",
    "../src/LexLua.cxx",
    "../src/LexMagik.cxx",
    "../src/LexMarkdown.cxx",
    "../src/LexMatlab.cxx",
    "../src/LexMetapost.cxx",
    "../src/LexMMIXAL.cxx",
    "../src/LexMPT.cxx",
    "../src/LexMSSQL.cxx",
    "../src/LexMYSQL.cxx",
    "../src/LexNimrod.cxx",
    "../src/LexNsis.cxx",
    "../src/LexOpal.cxx",
    "../src/LexOthers.cxx",
    "../src/LexPascal.cxx",
    "../src/LexPB.cxx",
    "../src/LexPerl.cxx",
    "../src/LexPLM.cxx",
    "../src/LexPowerPro.cxx",
    "../src/LexPowerShell.cxx",
    "../src/LexPOV.cxx",
    "../src/LexProgress.cxx",
    "../src/LexPS.cxx",
    "../src/LexPython.cxx",
    "../src/LexR.cxx",
    "../src/LexRebol.cxx",
    "../src/LexRuby.cxx",
    "../src/LexScriptol.cxx",
    "../src/LexSML.cxx",
    "../src/LexSmalltalk.cxx",
    "../src/LexSorcus.cxx",
    "../src/LexSpecman.cxx",
    "../src/LexSpice.cxx",
    "../src/LexSQL.cxx",
    "../src/LexTACL.cxx",
    "../src/LexTADS3.cxx",
    "../src/LexTAL.cxx",
    "../src/LexTcl.cxx",
    "../src/LexTeX.cxx",
    "../src/LexUDL.cxx",
    "../src/LexVB.cxx",
    "../src/LexVerilog.cxx",
    "../src/LexVHDL.cxx",
    "../src/LexXSLT.cxx",
    "../src/LexYAML.cxx",
    "../src/LineMarker.cxx",
    "../src/LineMarker.h",
    "../src/Partitioning.h",
    "../src/PerLine.cxx",
    "../src/PerLine.h",
    "../src/PositionCache.cxx",
    "../src/PositionCache.h",
    "../src/PropSet.cxx",
    "../src/PropSetSimple.h",
    "../src/RESearch.cxx",
    "../src/RESearch.h",
    "../src/RunStyles.cxx",
    "../src/RunStyles.h",
    "../src/SVector.h",
    "../src/ScintillaBase.cxx",
    "../src/ScintillaBase.h",
    "../src/Selection.cxx",
    "../src/Selection.h",
    "../src/SplitVector.h",
    "../src/Style.cxx",
    "../src/Style.h",
    "../src/StyleContext.cxx",
    "../src/StyleContext.h",
    "../src/SVector.h",
    "../src/UniConversion.cxx",
    "../src/UniConversion.h",
    "../src/ViewStyle.cxx",
    "../src/ViewStyle.h",
    "../src/WindowAccessor.cxx",
    "../src/XPM.cxx",
    "../src/XPM.h",
    "Margin.cur",
    "PlatformRes.h",
    "PlatWin.cxx",
    "Scintilla.def",
    "ScintillaWin.cxx",
    "ScintRes.rc",
    "../bin/empty.txt",   # as for scintilla dist, only there to create bin dir

    "libpcre.lib", # built and installed from contrib/pcre
    "../include/pcre.h", # installed from contrib/pcre

    qq(
        $unsiloedPythonExe bin/run-in-dir.py %2:d python HFacer.py
        set LINK=$LDFLAGS && $unsiloedPythonExe bin/run-in-dir.py %1:d nmake /nologo QUIET=0 $pluginName -f %1:f
    )
);


# install it
$cons->Install($mozBin, $pluginName);

# Running regxpcom depends on SciLexer.dll being installed.
my $installedPluginPath = File::Spec->catfile($mozBin, basename($pluginName));
$cons->Depends($ranRegxpcomStateFileName, $installedPluginPath);
