#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'komodoPythonUtilsDir',
    'ranRegxpcomStateFileName',
    'platform',
    'buildType',
    'mozVersion',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'siloedPythonVersion',
    'supportDir',
    'mozVersion',
);

my $siloedPythonMajor;
my $siloedPythonMinor;
if ($siloedPythonVersion =~ /^(\d+)\.(\d+)/) {
    $siloedPythonMajor = $1;
    $siloedPythonMinor = $2;
}

$cons->InstallPythonUtility('uriparse.py');
$cons->InstallPythonUtility('HTMLTreeParser.py');
$cons->InstallPythonUtility('koXMLDatasetInfo.py');
$cons->InstallPythonUtility('koXMLTreeService.py');
$cons->InstallPythonUtility('koCatalog.py');
$cons->InstallPythonUtility('koSimpleLexer.py');
$cons->InstallPythonUtility('koDTD.py');
$cons->InstallPythonUtility('kotaclib.py');
$cons->InstallPythonUtility('koRNGElementTree.py');
$cons->InstallPythonUtility('koUnicodeEncoding.py');
$cons->InstallPythonUtility('eollib.py');
$cons->InstallPythonUtility('strptime.py');
$cons->InstallPythonUtility('koXMLPrefs.py');
$cons->InstallPythonUtility('process.py');
$cons->InstallPythonUtility('koprocessutils.py');
$cons->InstallPythonUtility('which.py');
$cons->Preprocess('koTreeView.p.py', 'koTreeView.py');
$cons->InstallPythonUtility('koTreeView.py');
$cons->InstallPythonUtility('pyxpcomProfiler.py');
$cons->InstallPythonUtility('reflow.py');
$cons->InstallPythonUtility('difflibex.py');
$cons->InstallPythonUtility('sitepyxpcom.py');
$cons->InstallPythonUtility('directoryServiceUtils.py');
$cons->InstallPythonUtility('applib.py');
$cons->InstallPythonUtility('textutils.py');
$cons->InstallPythonUtility('upgradeutils.py');
$cons->InstallPythonUtility('mozutils.py');
$cons->InstallPythonUtility('fileutils.py');
$cons->InstallPythonUtility('memutils.py');
$cons->InstallPythonUtility('thread_helper.py');

$cons->InstallPythonUtility('langinfo.py');
$cons->InstallPythonUtility('langinfo_binary.py');
$cons->InstallPythonUtility('langinfo_doc.py');
$cons->InstallPythonUtility('langinfo_komodo.py');
$cons->InstallPythonUtility('langinfo_mozilla.py');
$cons->InstallPythonUtility('langinfo_other.py');
$cons->InstallPythonUtility('langinfo_prog.py');
$cons->InstallPythonUtility('langinfo_template.py');
$cons->InstallPythonUtility('langinfo_tiny.py');
$cons->InstallPythonUtility('textinfo.py');
$cons->InstallPythonUtility('pythonVersionUtils.py');


if ($platform eq "win") {
    $cons->InstallPythonUtility('wininteg.py');
    $cons->InstallPythonUtility('ctypesutils.py');
    $cons->InstallPythonUtility('win32_named_pipe.py');
}

if ($buildFlavour eq "dev") {
    $cons->InstallPythonUtility('benchmark.py');
}
