#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'build',
    'platform',
    'productType',
    'buildFlavour',
    'buildType',
    'supportDir',
    'unsiloedPythonExe',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'mozVersion',
    'sdkDir',
    'mozSrc',
);


$cons->Install($idlExportDir, 'koILanguage.idl');
$cons->BuildAndInstallXpt('koILanguage.idl');
$cons->Preprocess('koPythonLanguage.p.py', 'koPythonLanguage.py');
$cons->InstallXpcomComponent('koPythonLanguage.py');
$cons->InstallXpcomComponent('koLanguage.py');
$cons->InstallPythonUtility('koLanguageServiceBase.py');
$cons->InstallPythonUtility('koLanguageKeywordBase.py');
$cons->InstallPythonUtility('koUDLLanguageBase.py');
$cons->InstallPythonUtility('koXMLLanguageBase.py');

$cons->InstallXpcomComponent('koADALanguage.py');
$cons->InstallXpcomComponent('koApacheLanguage.py');
$cons->InstallXpcomComponent('koAPDLLanguage.py');
$cons->InstallXpcomComponent('koAsmLanguage.py');
$cons->InstallXpcomComponent('koASN1Language.py');
$cons->InstallXpcomComponent('koAu3Language.py');
$cons->InstallXpcomComponent('koAVELanguage.py');
$cons->InstallXpcomComponent('koBaanLanguage.py');
$cons->InstallXpcomComponent('koBashLanguage.py');
$cons->InstallXpcomComponent('koBasicLanguage.py');
$cons->InstallXpcomComponent('koBATLanguage.py');
$cons->InstallXpcomComponent('koBullantLanguage.py');
$cons->InstallXpcomComponent('koCamlLanguage.py');
$cons->InstallXpcomComponent('koCLWLanguage.py');
$cons->InstallXpcomComponent('koCMakeLanguage.py');
$cons->InstallXpcomComponent('koCobolLanguage.py');
$cons->InstallXpcomComponent('koCPPLanguage.py');
$cons->InstallXpcomComponent('koCSharpLanguage.py');
$cons->InstallXpcomComponent('koCsoundLanguage.py');
$cons->InstallXpcomComponent('koCSSLanguage.py');
$cons->InstallXpcomComponent('koDiffLanguage.py');
$cons->InstallXpcomComponent('koEiffelLanguage.py');
$cons->InstallXpcomComponent('koErlangLanguage.py');
$cons->InstallXpcomComponent('koErrorLanguage.py');
$cons->InstallXpcomComponent('koEScriptLanguage.py');
$cons->InstallXpcomComponent('koFlagshipLanguage.py');
$cons->InstallXpcomComponent('koForthLanguage.py');
$cons->InstallXpcomComponent('koFortranLanguage.py');
$cons->InstallXpcomComponent('koGui4CliLanguage.py');
$cons->InstallXpcomComponent('koHaskellLanguage.py');
$cons->InstallXpcomComponent('koHLSLLanguage.py');
$cons->InstallXpcomComponent('koIDLLanguage.py');
$cons->InstallXpcomComponent('koIniLanguage.py');
$cons->InstallXpcomComponent('koJavaLanguage.py');
$cons->InstallXpcomComponent('koJavaScriptLanguage.py');
$cons->InstallXpcomComponent('koKixLanguage.py');
$cons->InstallXpcomComponent('koLispLanguage.py');
$cons->InstallXpcomComponent('koLoutLanguage.py');
$cons->InstallXpcomComponent('koLuaLanguage.py');
$cons->InstallXpcomComponent('koMakefileLanguage.py');
$cons->InstallXpcomComponent('koMarkdownLanguage.py');
$cons->InstallXpcomComponent('koMatlabLanguage.py');
$cons->InstallXpcomComponent('koMetapostLanguage.py');
$cons->InstallXpcomComponent('koMMIXALLanguage.py');
$cons->InstallXpcomComponent('koMPTLanguage.py');
$cons->InstallXpcomComponent('koMSSQLLanguage.py');
$cons->InstallXpcomComponent('konnCrontabLanguage.py');
$cons->InstallXpcomComponent('koNimrodLanguage.py');
$cons->InstallXpcomComponent('koNsisLanguage.py');
$cons->InstallXpcomComponent('koPascalLanguage.py');
$cons->InstallXpcomComponent('koPowerBasicLanguage.py');
$cons->InstallXpcomComponent('koPowerProLanguage.py');
$cons->InstallXpcomComponent('koPowerShellLanguage.py');
$cons->InstallXpcomComponent('koPerlLanguage.py');
$cons->InstallXpcomComponent('koPOVLanguage.py');
$cons->InstallXpcomComponent('koPostScriptLanguage.py');
$cons->InstallXpcomComponent('koREBOLLanguage.py');
$cons->InstallXpcomComponent('koRegexLanguage.py');
$cons->InstallXpcomComponent('koRubyLanguage.py');
$cons->InstallXpcomComponent('koRxLanguage.py');
$cons->InstallXpcomComponent('koScriptolLanguage.py');
$cons->InstallXpcomComponent('koSmalltalkLanguage.py');
$cons->InstallXpcomComponent('koSorcusLanguage.py');
$cons->InstallXpcomComponent('koSpecmanLanguage.py');
$cons->InstallXpcomComponent('koSQLLanguage.py');
$cons->InstallXpcomComponent('koSwiftLanguage.py');
$cons->InstallXpcomComponent('koTandemComputerLanguage.py');
$cons->InstallXpcomComponent('koTADS3Language.py');
$cons->Preprocess('koTclLanguage.p.py', 'koTclLanguage.py');
$cons->InstallXpcomComponent('koTclLanguage.py');
$cons->InstallXpcomComponent('koTeXLanguage.py');
$cons->InstallXpcomComponent('koTextLanguage.py');
$cons->InstallXpcomComponent('koVBLanguage.py');
$cons->InstallXpcomComponent('koVHDLLanguage.py');
$cons->InstallXpcomComponent('koVerilogLanguage.py');
$cons->InstallXpcomComponent('koYAMLLanguage.py');
