#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'readmeDir',
);

$cons->InstallAs("LICENSE.rtf", "LICENSE.mpl.rtf"); 
$cons->InstallAs("../LICENSE.txt", "LICENSE.mpl.txt"); 
$cons->InstallAs("$readmeDir/LICENSE.txt", "LICENSE.mpl.txt"); 




