#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'docDir',
    'mozChromeDir',
    'productType',
);

# install Komodo doc image files in chrome
$cons->Install("$docDir/img", 'as_logo_onwhite.gif');
$cons->Install("$docDir/img", 'greysmallbullet.png');
$cons->Install("$docDir/img", 'cc_attr_noncom_sharealike.png');
$cons->Install("$docDir/img", 'button_showhide_TOC.gif');
$cons->Install("$docDir/img", 'button_sync_TOC.gif');
$cons->Install("$docDir/img", 'komodo_graphic_onwhite.gif');
$cons->Install("$docDir/img", 'nav_unsel_left_.gif');
$cons->Install("$docDir/img", 'nav_unsel_right_.gif');
$cons->Install("$docDir/img", 'pdf.gif');
$cons->Install("$docDir/img", 'shim.gif');
$cons->Install("$docDir/img", 'x.gif');
$cons->Install("$docDir/img", 'viewgraphic.gif');
$cons->Install("$docDir/img", 'icon_check_error.png');
$cons->Install("$docDir/img", 'icon_check_inprogress.png');
$cons->Install("$docDir/img", 'icon_check_ok.png');
$cons->Install("$docDir/img", 'pm_column.gif');
$cons->Install("$docDir/img", 'FindNextResult.gif');
$cons->Install("$docDir/img", 'edit.gif');
$cons->Install("$docDir/img", 'plus.gif');
$cons->Install("$docDir/img", 'minus.gif');
$cons->Install("$docDir/img", 'leaf.gif');
$cons->Install("$docDir/img", 'delete.gif');
$cons->Install("$docDir/img", 'status_icon_add.png');
$cons->Install("$docDir/img", 'status_icon_conflict.png');
$cons->Install("$docDir/img", 'status_icon_delete.png');
$cons->Install("$docDir/img", 'status_icon_edit.png');
$cons->Install("$docDir/img", 'status_icon_ok.png');
$cons->Install("$docDir/img", 'status_icon_readonly.png');
$cons->Install("$docDir/img", 'status_icon_sync.png');
$cons->Install("$docDir/img", 'ignore_case.gif');
$cons->Install("$docDir/img", 'multiple_line.gif');
$cons->Install("$docDir/img", 'rx_button.png');
$cons->Install("$docDir/img", 'multi_single.gif');
$cons->Install("$docDir/img", 'single_line.gif');
$cons->Install("$docDir/img", 'verbose.gif');
$cons->Install("$docDir/img", 'projtb_add_butt.gif');
$cons->Install("$docDir/img", 'projtb_add_butt.png');
$cons->Install("$docDir/img", 'button_comp_props.gif');
$cons->Install("$docDir/img", 'editor_syncol.gif');
$cons->Install("$docDir/img", 'editor_autocomp.gif');
$cons->Install("$docDir/img", 'editor_calltips.gif');
$cons->Install("$docDir/img", 'rx_match.gif');
$cons->Install("$docDir/img", 'rx_matches.gif');
$cons->Install("$docDir/img", 'tourlet_arrow.gif');
$cons->Install("$docDir/img", 'FilterBuilder-16-16-8.png');
$cons->Install("$docDir/img", 'PerlApp-16-16-8.gif');
$cons->Install("$docDir/img", 'PerlCov-16-16-8.png');
$cons->Install("$docDir/img", 'PerlCtrl-16-16-8.gif');
$cons->Install("$docDir/img", 'PerlNET-16-16-8.png');
$cons->Install("$docDir/img", 'PerlSvc-16-16-8.gif');
$cons->Install("$docDir/img", 'PerlTray-16-16-8.gif');
$cons->Install("$docDir/img", 'VBSPerl-16-16-8.png');

# Graphics for Welcome to Komodo
$cons->Install("$docDir/img", 'bottom_pane.gif');
$cons->Install("$docDir/img", 'code_tab.gif');
$cons->Install("$docDir/img", 'dom_tab.png');
$cons->Install("$docDir/img", 'editor_pane.gif');
$cons->Install("$docDir/img", 'main_menu.png');
$cons->Install("$docDir/img", 'project_tab.gif');
$cons->Install("$docDir/img", 'shared_toolbox_tab.gif');
$cons->Install("$docDir/img", 'start_page.png');
$cons->Install("$docDir/img", 'tab_cntxt_menu.gif');
$cons->Install("$docDir/img", 'title_bar.gif');
$cons->Install("$docDir/img", 'toolbar_debug.png');
$cons->Install("$docDir/img", 'toolbar_macro.png');
$cons->Install("$docDir/img", 'toolbar_open_find.png');
$cons->Install("$docDir/img", 'toolbar_pdk.png');
$cons->Install("$docDir/img", 'toolbar_scc.png');
$cons->Install("$docDir/img", 'toolbar_std.png');
$cons->Install("$docDir/img", 'toolbar_tools.png');
$cons->Install("$docDir/img", 'toolbar_wkspc.png');
$cons->Install("$docDir/img", 'toolbox_tab.gif');

# Graphics for Project
$cons->Install("$docDir/img", 'project_new_project.gif');
$cons->Install("$docDir/img", 'project_new_project.png');

# Graphics for the Run Command tutorial.
$cons->Install("$docDir/img", "runcommand_adv.gif");
$cons->Install("$docDir/img", "runcommand_ask1.gif");
$cons->Install("$docDir/img", "runcommand_ask2.gif");
$cons->Install("$docDir/img", "runcommand_findinfiles.gif");
$cons->Install("$docDir/img", "runcommand_icon.gif");
$cons->Install("$docDir/img", "runcommand_outputwin.gif");
$cons->Install("$docDir/img", "runcommand_parsedoutput.gif");
$cons->Install("$docDir/img", "runcommand_parsedviewbutton.gif");
$cons->Install("$docDir/img", "runcommand_project.gif");
$cons->Install("$docDir/img", "runcommand_properties.gif");
$cons->Install("$docDir/img", "runcommand_recent.gif");
$cons->Install("$docDir/img", "runcommand_shortcuts.gif");
$cons->Install("$docDir/img", "runcommand_simple.gif");
$cons->Install("$docDir/img", "runcommand_terminatebutton.gif");
$cons->Install("$docDir/img", "runcommand_toolbox.gif");

# Graphics for the tourlet_faststr
$cons->Install("$docDir/img", "tourlet_faststr_find.gif");
$cons->Install("$docDir/img", "tourlet_faststr_findin.gif");
$cons->Install("$docDir/img", "tourlet_faststr_findres.gif");
$cons->Install("$docDir/img", "tourlet_faststr_search.gif");
$cons->Install("$docDir/img", "tourlet_faststr_string.gif");

# Graphics for the tourlet_custtoolbar
$cons->Install("$docDir/img", "tourlet_custtoolbar_final.gif");
$cons->Install("$docDir/img", "tourlet_custtoolbar_icon.gif");
$cons->Install("$docDir/img", "tourlet_custtoolbar_items.gif");
$cons->Install("$docDir/img", "tourlet_custtoolbar_newtoolbar.gif");
$cons->Install("$docDir/img", "tourlet_custtoolbar_props.gif");

# Graphics for the tourlet_incrsrch
$cons->Install("$docDir/img", "tourlet_incrsrch_invoke.gif");
$cons->Install("$docDir/img", "tourlet_incrsrch_next.gif");
$cons->Install("$docDir/img", "tourlet_incrsrch_nextfile.gif");
$cons->Install("$docDir/img", "tourlet_incrsrch_selstr.gif");

# Graphics for the tourlet_openfind
$cons->Install("$docDir/img", "tourlet_openfind_arrows.gif");
$cons->Install("$docDir/img", "tourlet_openfind_findfile.gif");
$cons->Install("$docDir/img", "tourlet_openfind_frontslash.gif");
$cons->Install("$docDir/img", "tourlet_openfind_poscursor.gif");
$cons->Install("$docDir/img", "tourlet_openfind_reducedisp.gif");
$cons->Install("$docDir/img", "tourlet_openfind_subdir.gif");

# Graphics for the tourlet_codecomp
$cons->Install("$docDir/img", "tourlet_codecomp_addsnip.png");
$cons->Install("$docDir/img", "tourlet_codecomp_inssnip.gif");
$cons->Install("$docDir/img", "tourlet_codecomp_snipconfig.gif");

# Graphics for the tourlet_viewcss
$cons->Install("$docDir/img", "tourlet_viewcss_chngcss.gif");
$cons->Install("$docDir/img", "tourlet_viewcss_sethtml.gif");
$cons->Install("$docDir/img", "tourlet_viewcss_setpref.gif");
$cons->Install("$docDir/img", "tourlet_viewcss_viewout.gif");

# Graphics for the tourlet_snipinput
$cons->Install("$docDir/img", "tourlet_snipinput_config.png");
$cons->Install("$docDir/img", "tourlet_snipinput_insert.png");
$cons->Install("$docDir/img", "tourlet_snipinput_prompt.png");

# Graphics for the tourlet_googrun
$cons->Install("$docDir/img", "tourlet_googrun_googres.gif");
$cons->Install("$docDir/img", "tourlet_googrun_runcmd.gif");
$cons->Install("$docDir/img", "tourlet_googrun_srchterm.gif");
$cons->Install("$docDir/img", "tourlet_googrun_toolbox.gif");

# Graphics for the tourlet_googrun

$cons->Install("$docDir/img", "tourlet_intshell_editor.gif");
$cons->Install("$docDir/img", "tourlet_intshell_editor2.gif");
$cons->Install("$docDir/img", "tourlet_intshell_help.gif");
$cons->Install("$docDir/img", "tourlet_intshell_help2.gif");
$cons->Install("$docDir/img", "tourlet_intshell_import.gif");
$cons->Install("$docDir/img", "tourlet_intshell_openshell.gif");

# Graphics for the tourlet_filesys

$cons->Install("$docDir/img", "tourlet_filesys_import.gif");
$cons->Install("$docDir/img", "tourlet_filesys_menu.gif");
$cons->Install("$docDir/img", "tourlet_filesys_struct.gif");

# Graphics for the tourlet_tempproj

$cons->Install("$docDir/img", "tourlet_tempproj_addtoolbox.gif");
$cons->Install("$docDir/img", "tourlet_tempproj_file.gif");
$cons->Install("$docDir/img", "tourlet_tempproj_project.gif");
$cons->Install("$docDir/img", "tourlet_tempproj_save.gif");

#Graphics for tourlet_dirshortcut

$cons->Install("$docDir/img", "tourlet_dirshortcut_add.gif");
$cons->Install("$docDir/img", "tourlet_dirshortcut_open.gif");
$cons->Install("$docDir/img", "tourlet_dirshortcut_select.gif");

#Graphics for tourlet_reuse
$cons->Install("$docDir/img", "tourlet_reuse_select.png");
$cons->Install("$docDir/img", "tourlet_reuse_drop.png");

# Graphics for the tourlet_keybinding
$cons->Install("$docDir/img", "tourlet_keybinding_add.gif");
$cons->Install("$docDir/img", "tourlet_keybinding_props.gif");
$cons->Install("$docDir/img", "tourlet_keybinding_tab.gif");

# Graphics for the tourlet_expimppkg
$cons->Install("$docDir/img", "tourlet_expimppkg_exp.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_files.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_folder.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_foldername.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_imp.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_location.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_name.gif");
$cons->Install("$docDir/img", "tourlet_expimppkg_wiz.gif");

# Graphics for the Welcome page
$cons->Install("$docDir/img/top", "top/as-logo.png");
$cons->Install("$docDir/img/top", "top/box-features-bg.png");
$cons->Install("$docDir/img/top", "top/box-left-bg.png");
$cons->Install("$docDir/img/top", "top/box-right-bg.png");
$cons->Install("$docDir/img/top", "top/box-sample-bg.png");
$cons->Install("$docDir/img/top", "top/box-tutorials-bg.png");
$cons->Install("$docDir/img/top", "top/docs-top-bg.png");
$cons->Install("$docDir/img/top", "top/komodo-is.png");
$cons->Install("$docDir/img/top", "top/bug-icon.png");
$cons->Install("$docDir/img/top", "top/community-icon.png");
$cons->Install("$docDir/img/top", "top/forums-icon.png");

