#!/usr/local/bin/perl
# Copyright (c) 2010 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'buildFlavour',
    'sdkDir',
    'build',
    'mozBin',
    'unsiloedPythonExe',
);


$cons->KoExtUnpack(SourcePath("crystal.xpi"));
