#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'mozChromeDir',
    'platform',
    'buildFlavour',
    'unsiloedPythonExe',
    'mozVersion',
    'productType',
);

$cons->Preprocess('startpage.unprocessed.xml', 'startpage.xml');
$cons->InstallInChrome('startpage.xml');

