# bk.cpp -> bk.exe

# for release:
CFLAGS=-D_CONSOLE -D_MBCS -DWIN32 -W3 -Ox -DNDEBUG -D_NDEBUG -MD 
LDFLAGS=/subsystem:console kernel32.lib user32.lib gdi32.lib advapi32.lib shlwapi.lib
# for debug:
#  CFLAGS = -D_CONSOLE -D_MBCS /DWIN32 /Zi /Od /DDEBUG /D_DEBUG /MDd
#  LDFLAGS += /DEBUG

bk.exe: bk.cpp
	cl -nologo $(CFLAGS) -c bk.cpp
	link -nologo $(LDFLAGS) bk.obj

clean:
	del bk.obj
    del bk.exe
