#!/usr/local/bin/perl

# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

# Conscript for building the scintilla dll (with lexer)
#   Neil Hodgson provides a makefile to build this so we are no going to
#   duplicate that, however, to ensure rebuilding as necessary the
#   Command that call the makefile should have the proper dependencies
#   (i.e. inputs). In fact, to work with the build->src link they *must* all
#   be listed (this is a good thing). These will have to be kept in sync.

Import(
    'cons',
    'buildType',
    'mozPluginsDir',
    'unsiloedPythonExe',
    'scintillaBuildDir',
    'architecture',
    'mozBin',
);

# this is what we want from the scintilla build process
$libName = '../bin/libscintilla.dylib';

# build scintilla
my $makeFlags = "-DCONTAINER_HANDLES_EVENTS=1 -DINCLUDE_DEPRECATED_FEATURES";
if ($buildType eq 'debug') {
    $makeFlags .= " -DDEBUG=1";
}

# The SciMoz build on Linux explicitly links the Lex*.o files from the
# scintilla build AND with Cons multiple targets for a "Command" cannot be
# specified, so have to specify a makefile call for each platform.
# Use one entry per line for ease of maintenance.  Bits are cheap.
my @lexers = qw(
    Ada
    APDL
    Asn1
    AU3
    Abaqus
    Asm
    ASY
    AVE
    Baan
    Bash
    Basic
    Bullant
    Caml
    CoffeeScript
    Conf
    COBOL
    CPP
    CSS
    CLW
    Cmake
    Crontab
    Csound
    D
    Eiffel
    EScript
    Erlang
    Flagship
    Forth
    Fortran
    GAP
    Gui4Cli
    Haskell
    HTML
    Inno
    Kix
    Lisp
    Lout
    Lua
    Magik
    Markdown
    Matlab
    Metapost
    MMIXAL
    MPT
    MSSQL
    MySQL
    Nimrod
    Nsis
    Opal
    Others
    PB
    PLM
    Pascal
    Perl
    PowerShell
    PowerPro
    PS
    Python
    POV
    Progress
    R
    Rebol
    Ruby
    Scriptol
    Smalltalk
    SML
    Sorcus
    Specman
    SQL
    Spice
    TACL
    TADS3
    TAL
    TeX
    Tcl
    UDL
    VB
    Verilog
    VHDL
    XSLT
    YAML
);

my @args = (
    # the generated files
    # More specifically: the generated files that other segments of the Cons
    # system care about.
    [$libName],
    # the files needed to generate these
    "makefile",
    "deps.mak",
    "../include/Accessor.h",
    "../include/Face.py",
    "../include/HFacer.py",
    "../include/KeyWords.h",
    "../include/Platform.h",
    "../include/PropSet.h",
    "../include/SString.h",
    "../include/SciLexer.h",
    "../include/Scintilla.h",
    "../include/Scintilla.iface",
    "../include/ScintillaWidget.h",
    "../include/WindowAccessor.h",
    "../src/AutoComplete.cxx",
    "../src/AutoComplete.h",
    "../src/CallTip.cxx",
    "../src/CallTip.h",
    "../src/CellBuffer.cxx",
    "../src/CellBuffer.h",
    "../src/CharClassify.cxx",
    "../src/CharClassify.h",
    "../src/CharacterSet.h",
    "../src/ContractionState.cxx",
    "../src/ContractionState.h",
    "../src/Decoration.cxx",
    "../src/Decoration.h",
    "../src/Document.cxx",
    "../src/Document.h",
    "../src/DocumentAccessor.cxx",
    "../src/DocumentAccessor.h",
    "../src/Editor.cxx",
    "../src/Editor.h",
    "../src/ExternalLexer.cxx",
    "../src/ExternalLexer.h",
    "../src/FontQuality.h",
    "../src/Indicator.cxx",
    "../src/Indicator.h",
    "../src/KeyMap.cxx",
    "../src/KeyMap.h",
    "../src/KeyWords.cxx",
    "../src/LineMarker.cxx",
    "../src/LineMarker.h",
    "../src/Partitioning.h",
    "../src/PerLine.cxx",
    "../src/PerLine.h",
    "../src/PositionCache.cxx",
    "../src/PositionCache.h",
    "../src/PropSet.cxx",
    "../src/PropSetSimple.h",
    "../src/RESearch.cxx",
    "../src/RESearch.h",
    "../src/RunStyles.cxx",
    "../src/RunStyles.h",
    "../src/SVector.h",
    "../src/ScintillaBase.cxx",
    "../src/ScintillaBase.h",
    "../src/Selection.cxx",
    "../src/Selection.h",
    "../src/SplitVector.h",
    "../src/Style.cxx",
    "../src/Style.h",
    "../src/StyleContext.cxx",
    "../src/StyleContext.h",
    "../src/SVector.h",
    "../src/UniConversion.cxx",
    "../src/UniConversion.h",
    "../src/ViewStyle.cxx",
    "../src/ViewStyle.h",
    "../src/WindowAccessor.cxx",
    "../src/XPM.cxx",
    "../src/XPM.h",
    "PlatMacOSX.cxx",
    "PlatMacOSX.h",
    "QuartzTextLayout.h",
    "QuartzTextStyle.h",
    "QuartzTextStyleAttribute.h",
    "ScintillaCallTip.cxx",
    "ScintillaCallTip.h",
    "ScintillaMacOSX.cxx",
    "ScintillaMacOSX.h",
    "TCarbonEvent.cxx",
    "TCarbonEvent.h",
    "TRect.h",
    "TView.cxx",
    "TView.h",
    "../bin/empty.txt",   # as for scintilla dist, only there to create bin dir

    "libpcre.a", # built and installed from contrib/pcre
    "../include/pcre.h", # installed from contrib/pcre

            );

sub _addLexer {
    my $cons = shift;
    my $name = shift;

    push(@args, "../src/Lex$name.cxx");
}

map { _addLexer($cons, $_); } @lexers;

%consLocal = $cons->copy();
$consLocal{ENV}{'CXXFLAGS'} .= " $makeFlags";
# scintilla has no visibility markers, so don't default to hidden
$consLocal{ENV}{'CXXFLAGS'} =~ s/-fvisibility=hidden//;
$consLocal{ENV}{'LDFLAGS'} .= " $makeFlags";
$consLocal = new cons(%consLocal);

push(@args, (qq(
             $unsiloedPythonExe bin/run-in-dir.py %1:d/../include/ chmod a+w Scintilla.h
             $unsiloedPythonExe bin/run-in-dir.py %1:d/../include/ chmod a+w SciLexer.h
             $unsiloedPythonExe bin/run-in-dir.py %1:d/../include/ python HFacer.py
             $unsiloedPythonExe bin/run-in-dir.py %1:d chmod a+w deps.mak
             $unsiloedPythonExe bin/run-in-dir.py %1:d make deps
             $unsiloedPythonExe bin/run-in-dir.py %1:d make shared NATIVE=1 -f %1:f $libName
	     $unsiloedPythonExe bin/run-in-dir.py %1:d cp $libName $mozBin
             ))
     );

$consLocal->Command(@args);




