#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'docDir',
);

# install Komodo doc image files in chrome
$cons->Install("$docDir/tutorial", 'tourlet_over.html');
$cons->Install("$docDir/tutorial", 'tourlet_faststr.html');
$cons->Install("$docDir/tutorial", 'tourlet_custtoolbar.html');
$cons->Install("$docDir/tutorial", 'tourlet_incrsrch.html');
$cons->Install("$docDir/tutorial", 'tourlet_openfind.html');
$cons->Install("$docDir/tutorial", 'tourlet_codecomp.html');
$cons->Install("$docDir/tutorial", 'tourlet_viewcss.html');
$cons->Install("$docDir/tutorial", 'tourlet_snipinput.html');
$cons->Install("$docDir/tutorial", 'tourlet_googrun.html');
$cons->Install("$docDir/tutorial", 'tourlet_filesys.html');
$cons->Install("$docDir/tutorial", 'tourlet_tempproj.html');
$cons->Install("$docDir/tutorial", 'tourlet_dirshortcut.html');
$cons->Install("$docDir/tutorial", 'tourlet_reuse.html');
$cons->Install("$docDir/tutorial", 'tourlet_keybinding.html');
$cons->Install("$docDir/tutorial", 'tourlet_expimppkg.html');
