# confvars.sh - configure defaults for komodo, Gecko 24
MOZ_OJI=
XPC_IDISPATCH_SUPPORT=
MOZ_NO_ACTIVEX_SUPPORT=1
MOZ_ACTIVEX_SCRIPTING_SUPPORT=
MOZ_UPDATER=1
MOZ_HELP_VIEWER=1
MOZ_APP_NAME=komodo
MOZ_APP_DISPLAYNAME=KomodoEdit
MOZ_APP_UA_NAME=KomodoEdit
MOZ_KOMODO=1
