# Dialog.tcl --
#
# Generated by GUI Builder v1.0 on 2002-09-11 14:26:49 from:
#	C:/depot/main/Apps/Komodo-devel/src/samples/Dialog.ui
# This file is auto-generated.  It may be modified with the
# following restrictions:
#	1. Only code inside procs is round-tripped.
#

# Declare the namespace for this dialog
namespace eval Dialog {}

# Source the file, which must exist
source [file join [file dirname [info script]] Dialog_ui.tcl]
# Dialog::button_1_command --
#
# Here we create a command that handles the 
# -command option for the widget button_1
#
# ARGS:
#
proc Dialog::button_1_command args {}



# Standalone Code Initialization

# Dialog::init --
#
#   Call the optional userinit and initialize the dialog.
#   Do not edit this procedure.
#
# Arguments:
#   root   the root window to load this dialog into
#
# Results:
#   dialog will be created, or a background error will be thrown
#
proc Dialog::init {root args} {
    # Catch this in case the user didn't define it
    catch {Dialog::userinit}
    if {[info exists embed_args]} {
	# we are running in the plugin
	Dialog::ui $root
    } elseif {$::argv0 == [info script]} {
	# we are running in stand-alone mode
	wm title $root Dialog
	if {[catch {
	    # Create the UI
	    Dialog::ui  $root
	} err]} {
	    bgerror $err ; exit 1
	}
    }
    catch {Dialog::run $root}
}
Dialog::init .

