# Dialog_ui.tcl --
#
# UI generated by GUI Builder v1.0 on 2002-09-11 14:26:49 from:
#	C:/depot/main/Apps/Komodo-devel/src/samples/Dialog.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval Dialog {}

# Dialog::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc Dialog::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base


    # Widget Initialization
    button $base.button_1 \
	    -command [namespace code [list button_1_command]] \
	    -text button


    # Geometry Management

    grid $base.button_1 -in $root -row 1 -column 1

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 40 -pad 0
}
