# dlg_perl_scrolllist_ui.pl --
#
# UI generated by GUI Builder v1.0on 2002-09-12 10:44:06 from:
#	uiC:/p4/depot/main/Apps/Komodo-devel/src/samples/dlg_perl_scrolllist_ui.pl
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the package for this dialog
package dlg_perl_scrolllist;

use Tk;
use Tk::Menu;

# dlg_perl_scrolllist::ui --
#
# ARGS:
#   root     the parent window for this form
#
sub dlg_perl_scrolllist::ui {
    our($root) = @_;


    # Widget Initialization
    our($frame_1) = $root->Frame(
    );
    our($theLabel) = $root->Label(
	-anchor => 'w',
	-font => '{MS Sans Serif} 8 bold roman',
	-text => 'Insert data into the listbox:',
    );
    our($myListbox) = $root->Listbox(
	-exportselection => '0',
	-font => '{MS Sans Serif} 8 normal roman',
	-width => '0',
    );
    our($vertScrollbar) = $root->Scrollbar(
    );
    our($horizScrollbar) = $root->Scrollbar(
	-orient => 'horizontal',
    );
    our($insertButton) = $root->Button(
	-text => 'Insert Element',
	-width => '12',
    );
    our($exitButton) = $root->Button(
	-text => 'Exit',
	-width => '8',
    );

    # widget commands

    $myListbox->configure(
	-xscrollcommand => [set => $horizScrollbar]
    );
    $myListbox->configure(
	-yscrollcommand => [set => $vertScrollbar]
    );
    $vertScrollbar->configure(
	-command => [yview => $myListbox]
    );
    $horizScrollbar->configure(
	-command => [xview => $myListbox]
    );
    $insertButton->configure(
	-command => \&insertButton_command
    );
    $exitButton->configure(
	-command => sub { exit; }
    );


    # Geometry Management
    $frame_1->grid(
	-in     => $root,
	-column => '1',
	-row    => '4',
	-columnspan => '2',
	-sticky => 'nesw'
    );
    $theLabel->grid(
	-in     => $root,
	-column => '1',
	-row    => '1',
	-columnspan => '2',
	-sticky => 'nesw'
    );
    $myListbox->grid(
	-in     => $root,
	-column => '1',
	-row    => '2',
	-sticky => 'nesw'
    );
    $vertScrollbar->grid(
	-in     => $root,
	-column => '2',
	-row    => '2',
	-sticky => 'ns'
    );
    $horizScrollbar->grid(
	-in     => $root,
	-column => '1',
	-row    => '3',
	-sticky => 'ew'
    );
    $insertButton->grid(
	-in     => $frame_1,
	-column => '1',
	-row    => '1'
    );
    $exitButton->grid(
	-in     => $frame_1,
	-column => '2',
	-row    => '1'
    );


    # Resize Behavior
    $root->gridRowconfigure(1, -weight => 0, -minsize => 5, -pad => 0);
    $root->gridRowconfigure(2, -weight => 1, -minsize => 170, -pad => 0);
    $root->gridRowconfigure(3, -weight => 0, -minsize => 13, -pad => 0);
    $root->gridRowconfigure(4, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(1, -weight => 1, -minsize => 143, -pad => 0);
    $root->gridColumnconfigure(2, -weight => 0, -minsize => 2, -pad => 0);
    $frame_1->gridRowconfigure(1, -weight => 0, -minsize => 40, -pad => 0);
    $frame_1->gridColumnconfigure(1, -weight => 1, -minsize => 40, -pad => 0);
    $frame_1->gridColumnconfigure(2, -weight => 1, -minsize => 40, -pad => 0);
}

1;
