# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

""" dlg_py_showfile.py --

 UI generated by GUI Builder v1.0
 2002-09-12 10:46:50 from:
	C:/p4/depot/main/Apps/Komodo-devel/src/samples/dlg_py_showfile.ui
 This file is auto-generated.  It may be modified with the
 following restrictions:
    1. Only code inside 'def' functions is round-tripped.
"""

from Tkinter import *
from dlg_py_showfile_ui import Dlg_py_showfile
class CustomDlg_py_showfile(Dlg_py_showfile):

    # loadfile --
    #
    # Legacy command found in code. 
    # Add user comments inside body.
    def loadfile(self):
        "Get a filename and load it into the text widget"
        import tkFileDialog
        filename = tkFileDialog.askopenfilename()
        if filename:
            fid  = open(filename)
            self.theTextWidget.delete(1.0, "end")
            self.theTextWidget.insert(1.0, fid.read())
            fid.close()

    # doexit --
    #
    # Legacy command found in code. 
    # Add user comments inside body.
    def doexit(self):
        sys.exit(0)


    # Standalone Code Initialization

def main():
    root = Tk()
    demo = CustomDlg_py_showfile(root)
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__':
    main()