# dlg_tcl_check.tcl --
#
# Generated by GUI Builder v1.0 on 2002-09-12 10:12:04 from:
#	C:/p4/depot/main/Apps/Komodo-devel/src/samples/dlg_tcl_check.ui
# This file is auto-generated.  It may be modified with the
# following restrictions:
#	1. Only code inside procs is round-tripped.
#

# Declare the namespace for this dialog
namespace eval dlg_tcl_check {}

# Source the file, which must exist
source [file join [file dirname [info script]] dlg_tcl_check_ui.tcl]
# dlg_tcl_check::checkbutton_1_command --
#
# Here we create a command that handles the 
# -command option for the widget checkbutton_1
#
# ARGS:
#
proc dlg_tcl_check::checkbutton_1_command args {
    variable BASE
    set state [expr {$::example_checkbutton ? "normal" : "disabled"}]
    $BASE.radio   configure -state $state
    $BASE.freedom configure -state $state
    $BASE.liberty configure -state $state
}

# dlg_tcl_check::radio_command --
#
# Here we create a command that handles the 
# -command option for the widget radio
#
# ARGS:
#
proc dlg_tcl_check::radio_command args {}

# dlg_tcl_check::freedom_command --
#
# Here we create a command that handles the 
# -command option for the widget freedom
#
# ARGS:
#
proc dlg_tcl_check::freedom_command args {}

# dlg_tcl_check::liberty_command --
#
# Here we create a command that handles the 
# -command option for the widget liberty
#
# ARGS:
#
proc dlg_tcl_check::liberty_command args {}

# dlg_tcl_check::userinit --
#
# Legacy command found in code. 
# Add user comments inside body.
#
# ARGS:
#
proc dlg_tcl_check::userinit args {
    set ::example_radiobutton ""
}



# Standalone Code Initialization

# dlg_tcl_check::init --
#
#   Call the optional userinit and initialize the dialog.
#   Do not edit this procedure.
#
# Arguments:
#   root   the root window to load this dialog into
#
# Results:
#   dialog will be created, or a background error will be thrown
#
proc dlg_tcl_check::init {root args} {
    # Catch this in case the user didn't define it
    catch {dlg_tcl_check::userinit}
    if {[info exists embed_args]} {
	# we are running in the plugin
	dlg_tcl_check::ui $root
    } elseif {$::argv0 == [info script]} {
	# we are running in stand-alone mode
	wm title $root dlg_tcl_check
	if {[catch {
	    # Create the UI
	    dlg_tcl_check::ui  $root
	} err]} {
	    bgerror $err ; exit 1
	}
    }
    catch {dlg_tcl_check::run $root}
}
dlg_tcl_check::init .

