""" dlg_py_showfile.py --

 UI generated by GUI Builder v1.0
 2002-09-12 10:46:50 from:
	C:/p4/depot/main/Apps/Komodo-devel/src/samples/dlg_py_showfile.ui
 This file is auto-generated.  It may be modified with the
 following restrictions:
    1. Only code inside 'def' functions is round-tripped.
"""

from Tkinter import *
from dlg_py_showfile_ui import Dlg_py_showfile
class CustomDlg_py_showfile(Dlg_py_showfile):

    # loadfile --
    #
    # Legacy command found in code. 
    # Add user comments inside body.
    def loadfile(self):
        "Get a filename and load it into the text widget"
        import tkFileDialog
        filename = tkFileDialog.askopenfilename()
        if filename:
            fid  = open(filename)
            self.theTextWidget.delete(1.0, "end")
            self.theTextWidget.insert(1.0, fid.read())
            fid.close()

    # doexit --
    #
    # Legacy command found in code. 
    # Add user comments inside body.
    def doexit(self):
        sys.exit(0)


    # Standalone Code Initialization

def main():
    root = Tk()
    demo = CustomDlg_py_showfile(root)
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__':
    main()