# dlg_tcl_check_ui.tcl --
#
# UI generated by GUI Builder v1.0 on 2002-09-12 10:12:04 from:
#	C:/p4/depot/main/Apps/Komodo-devel/src/samples/dlg_tcl_check.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval dlg_tcl_check {}

# dlg_tcl_check::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc dlg_tcl_check::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base


    # Widget Initialization
    checkbutton $base.checkbutton_1 \
	    -anchor w \
	    -command [namespace code [list checkbutton_1_command]] \
	    -font {{MS Sans Serif} 10 normal roman} \
	    -text {Check it out} \
	    -variable example_checkbutton
    radiobutton $base.radio \
	    -anchor w \
	    -command [namespace code [list radio_command]] \
	    -state disabled \
	    -text {Radio Radio} \
	    -value radio \
	    -variable example_radiobutton
    radiobutton $base.freedom \
	    -anchor w \
	    -command [namespace code [list freedom_command]] \
	    -state disabled \
	    -text {Radio Freedom} \
	    -value freedom \
	    -variable example_radiobutton
    radiobutton $base.liberty \
	    -anchor w \
	    -command [namespace code [list liberty_command]] \
	    -state disabled \
	    -text {Radio Liberty} \
	    -value liberty \
	    -variable example_radiobutton
    button $base.okButton \
	    -command exit \
	    -default active \
	    -font {{MS Sans Serif} 8 bold roman} \
	    -text OK \
	    -width 8
    button $base.cancelButton \
	    -command exit \
	    -font {{MS Sans Serif} 8 normal italic} \
	    -text Cancel \
	    -width 8


    # Geometry Management

    grid $base.checkbutton_1 -in $root -row 1 -column 2 \
	    -columnspan 2 \
	    -sticky ew
    grid $base.radio -in $root -row 2 -column 2 \
	    -columnspan 2 \
	    -sticky ew
    grid $base.freedom -in $root -row 3 -column 2 \
	    -columnspan 2 \
	    -sticky ew
    grid $base.liberty -in $root -row 4 -column 2 \
	    -columnspan 2 \
	    -sticky ew
    grid $base.okButton -in $root -row 6 -column 1 \
	    -columnspan 2
    grid $base.cancelButton -in $root -row 6 -column 3 \
	    -columnspan 2

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 7 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 2 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 2 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 9 -pad 0
    grid rowconfigure $root 5 -weight 1 -minsize 10 -pad 0
    grid rowconfigure $root 6 -weight 0 -minsize 28 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $root 3 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $root 4 -weight 0 -minsize 40 -pad 0
}
