#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'build',
    'platform',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'supportDir',
    'unsiloedPythonExe',
    'productType',
    'buildFlavour',
    'mozVersion',
    'sdkDir',
    'mozSrc',
);

$cons->Preprocess('URIlib.p.py', 'URIlib.py');
$cons->InstallPythonUtility('URIlib.py');

$cons->Install($idlExportDir, 'koIFileEx.idl');
$cons->BuildAndInstallXpt('koIFileEx.idl');
$cons->InstallXpcomComponent('koFileEx.py');

$cons->Install($idlExportDir, 'koIFileService.idl');
$cons->BuildAndInstallXpt('koIFileService.idl');
$cons->InstallXpcomComponent('koFileService.py');

$cons->Install($idlExportDir, 'koIDocument.idl');
$cons->BuildAndInstallXpt('koIDocument.idl');
$cons->InstallXpcomComponent('koDocument.py');
$cons->InstallXpcomComponent('koDocumentService.py');

$cons->Install($idlExportDir, 'koIViews.idl');
$cons->BuildAndInstallXpt('koIViews.idl');

$cons->Install($idlExportDir, 'koIViewService.idl');
$cons->BuildAndInstallXpt('koIViewService.idl');
$cons->InstallXpcomComponent('koViewService.py');

$cons->Preprocess('koDocumentSettingsManager.p.py', 'koDocumentSettingsManager.py');
$cons->InstallXpcomComponent('koDocumentSettingsManager.py');

## Install test cases.
#$cons->Install("$supportDir/test", "test_URIlib.py");
#$cons->Install("$supportDir/test", "test_koDocument.py");
#$cons->Install("$supportDir/test", "test_koDocumentService.py");
#$cons->Install("$supportDir/test", "test_koFileEx.py");
#$cons->Install("$supportDir/test", "test_koFileService.py");

