#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

Import(
    'cons',
    'build',
    'mozChromeDir',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'unsiloedPythonExe',
    'jarring',
    'mozBin',
    'supportDir',
    'buildFlavour',
    'buildAbsDir',
    'buildType',
    'platform',
    'productType',
    'mozVersion',
    'mozExtensionDir',
);

# The Plan:
# - dev builds: Install the spellcheck extension with*out* jarring.
# - full (i.e. installer) builds: Install with jarring.

my $ext_name = "komodospellchecker";
my $ext_dir = "$mozExtensionDir/$ext_name\@ActiveState.com";

if ($buildFlavour eq "full") {
    $cons->Command(
        ["komodospellchecker.xpi", "komodospellchecker.jar"],
        "install.rdf",
        "chrome.manifest",
        "content/EdDialogCommon.js",
        "content/EdDictionary.js",
        "content/editorUtilities.js",
        "content/koDictionary.js",
        "content/koDictionary.xul",
        "content/koLaunchSpellcheck.js",
        "content/koSpellCheck.js",
        "content/koSpellCheckOverlay.xul",
        "content/koSpellCheck.xul",
        "locale/en-US/spellcheck.dtd",
        "locale/en-US/spellcheck.properties",
        qq(
           $unsiloedPythonExe bin/run-in-dir.py %1:d zip -X -Dr komodospellchecker.jar content locale
           $unsiloedPythonExe bin/run-in-dir.py %1:d zip -X komodospellchecker.xpi komodospellchecker.jar install.rdf chrome.manifest
        )
    );

    $cons->Install($ext_dir, 'komodospellchecker.jar');
    $cons->Install($ext_dir, 'install.rdf');
    $cons->Install($ext_dir, 'chrome.manifest');
}

else { # dev builds
    $cons->InstallAs("$ext_dir/chrome.manifest", 'devbuild.manifest');
    $cons->Install($ext_dir, 'install.rdf');

    my @content_files = (
        "content/EdDialogCommon.js",
        "content/EdDictionary.js",
        "content/editorUtilities.js",
        "content/koDictionary.js",
        "content/koDictionary.xul",
        "content/koLaunchSpellcheck.js",
        "content/koSpellCheck.js",
        "content/koSpellCheckOverlay.xul",
        "content/koSpellCheck.xul",
    );
    foreach my $file (@content_files) {
        $cons->Install("$ext_dir/content", $file);
    }
    $cons->Install("$ext_dir/locale/en-US", "locale/en-US/spellcheck.dtd");
    $cons->Install("$ext_dir/locale/en-US", "locale/en-US/spellcheck.properties");
}
