#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'unsiloedPythonExe',
    'jarring',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'mozVersion',
);

$cons->Preprocess('rxx.unprocessed.css', 'rxx.css');
$cons->InstallInChrome('rxx.css');

