/* Copyright (c) 2000-2006 ActiveState Software Inc.
   See the file LICENSE.txt for licensing information. */

#include "nsIDirectoryService.idl"

// Provides the URIs to Komodo files.
[scriptable, uuid(59180061-04d0-4f61-9549-2ee3bff7a4b9)]
interface koIDirs : nsISupports {
    readonly attribute wstring userDataDir;
    readonly attribute wstring hostUserDataDir; // host-specific dir under userDataDir
    readonly attribute wstring factoryCommonDataDir;
    readonly attribute wstring commonDataDir;
    // supportDir: Komodo's data support files directory somewhere in
    // the Komodo install tree.
    readonly attribute wstring supportDir;
    readonly attribute wstring sdkDir;
    readonly attribute wstring docDir;
    readonly attribute wstring installDir;
    readonly attribute wstring mozBinDir;
    readonly attribute wstring binDir;

    // DBGP-related directories.
    readonly attribute wstring binDBGPDir;
    readonly attribute wstring perlDBGPDir;
    readonly attribute wstring pythonDBGPDir;
};
