/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 * 
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is Komodo code.
 * 
 * The Initial Developer of the Original Code is ActiveState Software Inc.
 * Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
 * ActiveState Software Inc. All Rights Reserved.
 * 
 * Contributor(s):
 *   ActiveState Software Inc
 * 
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 * 
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

// Determine the functional status of various features in Komodo
// (Mainly this is to support part of the "feature control panel" on
// the Getting Started/Welcome page.)
//
// Data is exchanged with this service via the "feature_status_request"
// and "feature_status_ready" notifications. See
// internal-docs/howto-notifications.txt for details.
// 

[scriptable, uuid(1CD0AAEA-10E8-4B4A-9A7D-BE70C89CE250)]
interface koIFeatureStatus : nsISupports {
    // e.g. "Perl Debugging", "Python Syntax Checking")
    readonly attribute string featureName;
    // e.g. "Active", "Disabled"
    readonly attribute string status;
    // e.g. "Perl at C:\Perl is of version 5.005. At least version 5.6.0 is
    //       required."
    // This may be null if no reason is supplied.
    readonly attribute string reason;
};

[scriptable, uuid(6DF80015-E392-4B72-9428-7EDBB4D0350E)]
interface koIFeatureStatusService : nsISupports {
    // Data exchange is with nsIObserver notifications.
};


