/* Copyright (c) 2006 activestate.com
   See the file LICENSE.txt for licensing information. */

#include "nsISupports.idl"

/* a basic interface for getting some info from the catalog system so we can
 * display prefs, etc.
 */

[scriptable, uuid(e2497788-70fe-11db-9e86-000d935d3368)]
interface koIXMLCatalogService: nsISupports {
    // attributes, constants, methods, ...
    void getPublicIDList(out PRUint32 count,
                 [retval, array, size_is(count)] out wstring publicid);
    void getSystemIDList(out PRUint32 count,
                 [retval, array, size_is(count)] out wstring publicid);
    void getNamespaceList(out PRUint32 count,
                 [retval, array, size_is(count)] out wstring publicid);
};
