#!/usr/local/bin/perl
# Copyright (c) 2012 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'buildFlavour',
    'sdkDir',
    'build',
    'mozBin',
    'mozExtensionDir',
    'unsiloedPythonExe',
);

$cons->InstallAs("$mozExtensionDir/gtkstock\@developer.gnome.org.xpi", "gtkstock.xpi");
