#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'mozVersion',
);

$cons->InstallInChrome('prefs.js');

$cons->InstallInChrome('koPrefUtils.js');
$cons->InstallInChrome('koPrefWindow.js');
$cons->InstallInChrome('koFilteredPrefTree.js');

$cons->Preprocess('pref.p.xul', 'pref.xul');
$cons->InstallInChrome('pref.xul');
$cons->InstallInChrome('pref.js');

$cons->Preprocess('project.p.xul', 'project.xul');
$cons->InstallInChrome('project.xul');

$cons->InstallInChrome('pref-languages.xul');
$cons->InstallInChrome('pref-languages.js');

$cons->InstallInChrome('koPrefWidgets.xml');
$cons->InstallInChrome('editenvironvar.xul');
$cons->InstallInChrome('editenvironvar.js');

$cons->InstallInChrome('pref-xml-catalog.xul');

$cons->InstallInChrome('pref-editor.xul');
$cons->InstallInChrome('pref-indentation.xul');
$cons->InstallInChrome('pref-editsmart.xul');
$cons->InstallInChrome('pref-save.xul');

$cons->InstallInChrome('pref-association.xul');
$cons->InstallInChrome('pref-association.js');

$cons->InstallInChrome('pref-find.xul');

$cons->InstallInChrome('pref-python.xul');
$cons->InstallInChrome('pref-python.js');
$cons->InstallInChrome('pref-python3.xul');
$cons->InstallInChrome('pref-python3.js');

$cons->Preprocess('pref-javascript.p.xul', 'pref-javascript.xul');
$cons->InstallInChrome('pref-javascript.xul');
$cons->InstallInChrome('pref-javascript.js');

$cons->InstallInChrome('pref-nodejs.xul');
$cons->InstallInChrome('pref-nodejs.js');

$cons->Preprocess('pref-perl.p.xul', 'pref-perl.xul');
$cons->InstallInChrome('pref-perl.xul');
$cons->InstallInChrome('pref-perl.js');

$cons->Preprocess('pref-ruby.p.xul', 'pref-ruby.xul');
$cons->InstallInChrome('pref-ruby.xul');
$cons->InstallInChrome('pref-ruby.js');

$cons->Preprocess('pref-newfiles.p.xul', 'pref-newfiles.xul');
$cons->InstallInChrome('pref-newfiles.xul');
$cons->Preprocess('pref-newfiles.p.js', 'pref-newfiles.js');
$cons->InstallInChrome('pref-newfiles.js');

$cons->InstallInChrome('pref-intl.xul');
$cons->InstallInChrome('pref-intl.js');

$cons->Preprocess('pref-ui.p.xul', 'pref-ui.xul');
$cons->InstallInChrome('pref-ui.xul');

$cons->InstallInChrome('pref-ui.js');

$cons->InstallInChrome('pref-printing.xul');

$cons->InstallInChrome('pref-proxies.xul');
$cons->InstallInChrome('pref-proxies.js');

$cons->InstallInChrome('pref-servers.js');
$cons->Preprocess('pref-servers.p.xul', 'pref-servers.xul');
$cons->InstallInChrome('pref-servers.xul');

$cons->Preprocess('pref-php.p.xul', 'pref-php.xul');
$cons->InstallInChrome('pref-php.xul');
$cons->Preprocess('pref-php.p.js', 'pref-php.js');
$cons->InstallInChrome('pref-php.js');

$cons->Preprocess('pref-alllangfonts.p.xul', 'pref-alllangfonts.xul');
$cons->InstallInChrome('pref-alllangfonts.xul');
$cons->Preprocess('pref-alllangfonts.p.js', 'pref-alllangfonts.js');
$cons->InstallInChrome('pref-alllangfonts.js');

$cons->InstallInChrome('pref-web.xul');
$cons->Preprocess('pref-web.p.js', 'pref-web.js');
$cons->InstallInChrome('pref-web.js');

if ($platform eq "win") {
    $cons->InstallInChrome('pref-winInteg.xul');
    $cons->InstallInChrome('pref-winInteg.js');
    $cons->InstallInChrome('setupFileAssociations.xul');
    $cons->InstallInChrome('setupFileAssociations.js');
}
$cons->InstallInChrome('pref-environ.xul');
$cons->InstallInChrome('pref-environ.js');

$cons->Preprocess('pref-keys.p.xul', 'pref-keys.xul');
$cons->InstallInChrome('pref-keys.xul');
$cons->InstallInChrome('pref-keys.js');

$cons->InstallInChrome('pref-projects.xul');

$cons->Preprocess('pref-helplang.p.xul', 'pref-helplang.xul');
$cons->InstallInChrome('pref-helplang.xul');
$cons->Preprocess('pref-helplang.p.js', 'pref-helplang.js');
$cons->InstallInChrome('pref-helplang.js');

$cons->InstallInChrome('pref-html.xul');

$cons->Preprocess('pref-codeintel.p.xul', 'pref-codeintel.xul');
$cons->InstallInChrome('pref-codeintel.xul');
$cons->Preprocess('pref-codeintel.p.js', 'pref-codeintel.js');
$cons->InstallInChrome('pref-codeintel.js');

$cons->InstallInChrome('pref-mappeduri.xul');

$cons->InstallInChrome('pref-folderImport.xul');
$cons->InstallInChrome('project-folderImport.js');

$cons->Preprocess('file-properties.p.xul', 'file-properties.xul');
$cons->Preprocess('file-properties.p.js', 'file-properties.js');
$cons->InstallInChrome('file-advanced-properties.xul');
$cons->InstallInChrome('file-advanced-properties.js');
$cons->InstallInChrome('file-properties.xul');
$cons->InstallInChrome('file-properties.js');
$cons->InstallInChrome('file-permissions.xul');
$cons->InstallInChrome('pref-syntax-checking.xul');
$cons->InstallInChrome('pref-syntax-checking.js');
$cons->InstallInChrome('pref-jshint-options.xul');
$cons->InstallInChrome('pref-jshint-options.js');
$cons->InstallInChrome('preview-properties.js');
$cons->InstallInChrome('preview-properties.xul');
