#!/usr/local/bin/perl
# Copyright (c) 2010 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'build',
    'cons',
    'idlExportDir',
    'mozChromeDir',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'mozVersion',
    'ranRegxpcomStateFileName',
    'sdkDir',
    'unsiloedPythonExe',
    'komodoPythonUtilsDir',
);

$cons->Install($idlExportDir, 'koINotification.idl');
$cons->Install($idlExportDir, 'koINotificationManager.idl');
$cons->BuildAndInstallXpt('koINotification.idl');
$cons->BuildAndInstallXpt('koINotificationManager.idl');
$cons->InstallXpcomComponent('koNotificationManager.py');
$cons->Install($komodoPythonUtilsDir, 'koNotification.py');
$cons->BuildAndInstallXpt('koINotificationAsyncCallbackAdapter.idl');
$cons->InstallXpcomComponent('koNotificationAsyncCallbackAdapter.py');
