#!/usr/local/bin/perl
# Copyright (c) 2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'mozBin',
    'mozChromeDir',
);

$cons->InstallXpcomModule('notifications.js');

$cons->InstallInChrome('load-service.js');
$cons->InstallInChrome('notification.xml');
$cons->InstallInChrome('overlay.xul');
$cons->InstallInChrome('notificationsWidget.xul');
$cons->InstallInChrome('notificationsWidget.js');
