# confvars.sh - configure defaults for komodo, Gecko 1.9.1
MOZ_OJI=
XPC_IDISPATCH_SUPPORT=
MOZ_NO_ACTIVEX_SUPPORT=1
MOZ_ACTIVEX_SCRIPTING_SUPPORT=
MOZ_UPDATER=1
MOZ_HELP_VIEWER=1
MOZ_APP_NAME=komodo
MOZ_APP_DISPLAYNAME=Komodo
MOZ_KOMODO=1
