/* Copyright (c) 2006 [[%ask2:Domain Name:MyCompany.com]]
   See the file LICENSE.txt for licensing information. */

#include "nsISupports.idl"

/* ...description of component/service...
 *
 */

[scriptable, uuid([[%guid]])]
interface [[%ask1:Interface Name:iMyComponentInterface]]: nsISupports {
    // attributes, constants, methods, ...
};

