#!/usr/local/bin/perl
# Copyright (c) 2000-2010 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'build',
    'platform',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozChromeDir',
    'mozIdlIncludePath',
    'mozVersion',
    'idlExportDir',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'sdkDir',
);

$cons->Preprocess('toolboxPanel.p.xul', 'toolboxPanel.xul');
$cons->InstallInChrome('toolboxPanel.xul');
$cons->Preprocess('toolbox2.p.js', 'toolbox2.js');
$cons->InstallInChrome('toolbox2.js');
$cons->Preprocess('toolbox2_command.p.js', 'toolbox2_command.js');
$cons->InstallInChrome('toolbox2_command.js');
