#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    "cons",
    "mozChromeDir",
    "supportDir",
    "platform",
    "unsiloedPythonExe",
    "productType",
    "buildFlavour",
    "mozVersion",
);

my @samples = (
    ["sample_project.p.komodoproject", "sample_project.komodoproject"],
    ["perl_sample.p.pl", "perl_sample.pl"],
    ["python_sample.p.py", "python_sample.py"],
    ["python3_sample.p.py", "python3_sample.py"],
    ["ruby_sample.p.rb", "ruby_sample.rb"],
    ["javascript_sample.p.js", "javascript_sample.js"],
    ["php_sample.p.php", "php_sample.php"],
    ["tcl_sample.p.tcl", "tcl_sample.tcl"],
    ["xslt_sample.p.xsl", "xslt_sample.xsl"],
    ["birds.p.xml", "birds.xml"],
    ["html_sample.p.html", "html_sample.html"],
);
for $i (0 .. $#samples) {
    $cons->Preprocess($samples[$i][0], $samples[$i][1], undef, 1);
    $cons->InstallWriteable("$supportDir/samples", $samples[$i][1]);
}

