#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'build',
    'platform',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozChromeDir',
    'mozIdlIncludePath',
    'mozVersion',
    'idlExportDir',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
);

$cons->Preprocess('projectManager.p.js', 'projectManager.js');
$cons->InstallInChrome('projectManager.js');

$cons->InstallInChrome('partutils.js');

$cons->Preprocess('projectExtensionManager.p.js', 'projectExtensionManager.js');
$cons->InstallInChrome('projectExtensionManager.js');
$cons->InstallInChrome('baseManager.js');
$cons->Preprocess('toolboxManager.p.js', 'toolboxManager.js');
$cons->InstallInChrome('toolboxManager.js');
$cons->InstallInChrome('renamePart.xul');
$cons->InstallInChrome('macroProperties.xul');
$cons->InstallInChrome('macroProperties.js');
$cons->InstallInChrome('snippetProperties.js');
$cons->InstallInChrome('snippetProperties.xul');
$cons->InstallInChrome('simplePartProperties.xul');
$cons->InstallInChrome('simplePartProperties.js');
$cons->InstallInChrome('customMenuProperties.xul');
$cons->InstallInChrome('customMenuProperties.js');

$cons->Preprocess('peFile.p.js', 'peFile.js');
$cons->InstallInChrome('peFile.js');
$cons->Preprocess('peFolder.p.js', 'peFolder.js');
$cons->InstallInChrome('peFolder.js');
$cons->InstallInChrome('peSnippet.js');
$cons->InstallInChrome('peCommand.js');
$cons->InstallInChrome('peURL.js');
$cons->InstallInChrome('peMacro.js');
$cons->InstallInChrome('peMenu.js');
