#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'mozBin',
    'mozSrc',
    'unsiloedPythonExe',
    'jarring',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'mozVersion',
);

$cons->Preprocess('komodo.p.css', 'komodo.css');
$cons->InstallInChrome('komodo.css');
$cons->InstallInChrome('splitter.css');
$cons->Preprocess('toolbar.p.css', 'toolbar.css');
$cons->InstallInChrome('toolbar.css');
$cons->InstallInChrome('browser.css');
$cons->InstallInChrome('extmgr.css');
$cons->Preprocess('codeintel.p.css', 'codeintel.css');
$cons->InstallInChrome('codeintel.css');
$cons->InstallInChrome('hyperlinks.css');
$cons->InstallInChrome('tree.css');
$cons->InstallInChrome('autocomplete.css');
$cons->InstallInChrome('find.css');
$cons->InstallInChrome('feature_control_panel.css');
$cons->InstallInChrome('notifications.css');
$cons->InstallInChrome('_helpers/shortcuts.less');

$cons->Preprocess('templates/new.p.css', 'templates/new.css');
$cons->InstallInChrome('templates/new.css');

$cons->InstallInChrome('prefs/pref-window.less');
$cons->InstallInChrome('prefs/prefs.css');
$cons->InstallInChrome('prefs/pref-codeintel.css');

$cons->InstallInChrome('dialogs/customizeToolbar.css');
$cons->InstallInChrome('dialogs/find2.css');

if ($platform eq "darwin") {
    $cons->InstallRecursive("$mozChromeDir/komodo/skin/",
                            cwd()."/src/chrome/komodo/skin/plat/mac/",
                            ('\.svn', 'chrome\.manifest'));

    $cons->InstallRecursive("$mozChromeDir/komodo/skin/plat/current/",
                            cwd()."/src/chrome/komodo/skin/plat/mac/",
                            ('\.svn', 'chrome\.manifest'));

    $cons->InstallAs("$mozChromeDir/komodo/skin/plat/global.css",
                     "$mozChromeDir/toolkit/skin/classic/global/global.css");
} elsif ($platform eq "win") {
    $cons->InstallRecursive("$mozChromeDir/komodo/skin/",
                            cwd()."/src/chrome/komodo/skin/plat/win/",
                            ('\.svn', 'chrome\.manifest'));

    $cons->InstallRecursive("$mozChromeDir/komodo/skin/plat/current/",
                            cwd()."/src/chrome/komodo/skin/plat/win/",
                            ('\.svn', 'chrome\.manifest'));

    $cons->InstallAs("$mozChromeDir/komodo/skin/plat/global.css",
                     "$mozChromeDir/toolkit/skin/classic/global/global.css");
} else {
    $cons->InstallRecursive("$mozChromeDir/komodo/skin/",
                            cwd()."/src/chrome/komodo/skin/plat/gnome/",
                            ('\.svn', 'chrome\.manifest'));

    $cons->InstallRecursive("$mozChromeDir/komodo/skin/plat/current/",
                            cwd()."/src/chrome/komodo/skin/plat/gnome/",
                            ('\.svn', 'chrome\.manifest'));

    $cons->InstallAs("$mozChromeDir/komodo/skin/plat/global.css",
                     "$mozChromeDir/toolkit/skin/classic/global/global.css");
}

$cons->InstallRecursive("$mozChromeDir/komodo/skin/plat/shared/",
                        cwd()."/src/chrome/komodo/skin/plat/shared/",
                        ('\.svn', 'chrome\.manifest'));

$cons->InstallInChrome('iconset/config.less');
$cons->InstallInChrome('iconset/rules.less');

$cons->Preprocess('partials/scheme-skinning.p.less', 'partials/scheme-skinning.less');
$cons->InstallInChrome('partials/scheme-skinning.less');

$cons->InstallInChrome('filters.svg');

$cons->InstallInChrome('svg/defs/cupertino.xml');
$cons->InstallInChrome('svg/defs/cupertino-blue.xml');
