#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'build',
    'idlExportDir',
    'mozComponentsDir',
    'ranRegxpcomStateFileName',
    'mozIncludePath',
    'mozIdlIncludePath',
    'mozLibPath',
    'mozSrc',
    'mozDevelDist',
    'mozObjDir',
    'mozBin',
    'platform',
    'architecture',
    'buildType',
    'supportDir',
    'withSymbols',
    'unsiloedPerlExe',
    'unsiloedPythonExe',
    'mozVersion',
    'mozVersionNumber',
    'mozDist',
    'sdkDir',
);


$cons->InstallXpcomComponent('koJSONLinter.py');
$cons->Install("$supportDir/lint/json", "xpcshell_jsonlint.js");

