#!/usr/local/bin/perl
# Copyright (c) 2010 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'platform',
    'productType',
    'buildFlavour',
    'sdkDir',
    'build',
    'mozBin',
    'unsiloedPythonExe',
    'mozVersion',
    'mozExtensionDir',
);

my $local = 0;

if (!$local) {
    # Usually $buildFlavour is 'dev' on a dev box, -- full on a build machine?
    $cons->Preprocess("chrome.p.manifest", "chrome.manifest", {MODE => 'full'});
    $cons->KoExt("koinstall");
} else {
    print STDERR "Places: don't forget to reinstate regular koinstall by setting \$local to 0\n";
    $cons->Preprocess("chrome.p.manifest", "chrome.manifest", {MODE => 'dev'});
    # For quick development, comment out the "KoExt" call above and 
    # use this:
    $cons->KoExtSourceDevInstall();
}

