#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import('cons', 'mozChromeDir');

$cons->InstallInChrome('tail.js');
$cons->InstallInChrome('tail.xul');
