#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'unsiloedPythonExe',
    'productType',
    'jarring',
    'buildFlavour',
    'mozVersion',
);

$cons->Preprocess("prompt.p.js", "prompt.js");
$cons->InstallInChrome('prompt.js');
$cons->Preprocess("prompt.p.xul", "prompt.xul");
$cons->InstallInChrome('prompt.xul');
$cons->InstallInChrome('yesNoCancel.js');
$cons->InstallInChrome('yesNoCancel.xul');
$cons->InstallInChrome('yesNo.js');
$cons->InstallInChrome('yesNo.xul');
$cons->InstallInChrome('okCancel.js');
$cons->InstallInChrome('okCancel.xul');
$cons->InstallInChrome('alert.js');
$cons->InstallInChrome('alert.xul');
$cons->InstallInChrome('selectFromList.js');
$cons->InstallInChrome('selectFromList.xul');
$cons->InstallInChrome('customButtons.js');
$cons->InstallInChrome('customButtons.xul');
$cons->Preprocess('editEnvVar.p.js', 'editEnvVar.js');
$cons->InstallInChrome('editEnvVar.js');
$cons->InstallInChrome('editEnvVar.xul');
$cons->Preprocess('editPathMap.p.xul', 'editPathMap.xul');
$cons->InstallInChrome('editPathMap.xul');
$cons->InstallInChrome('internalError.js');
$cons->InstallInChrome('internalError.xul');
$cons->InstallInChrome('authenticate.js');
$cons->InstallInChrome('authenticate.xul');
$cons->InstallInChrome('pickPreview.js');
$cons->InstallInChrome('pickPreview.xul');

$cons->InstallInChrome('compare.js');
$cons->InstallInChrome('compare.xul');

$cons->InstallInChrome('diff.js');
$cons->Preprocess('diff.p.xul', 'diff.xul');
$cons->InstallInChrome('diff.xul');

$cons->Preprocess("featureControlPanel.p.js", "featureControlPanel.js");
$cons->InstallInChrome('featureControlPanel.js');
$cons->Preprocess("featureControlPanel.p.xul", "featureControlPanel.xul");
$cons->InstallInChrome('featureControlPanel.xul');

$cons->InstallInChrome('progress.js');
$cons->InstallInChrome('progress.xul');

$cons->InstallInChrome('iconpicker.js');
$cons->InstallInChrome('iconpicker.xul');

$cons->InstallInChrome('customizeToolbar.js');
$cons->InstallInChrome('customizeToolbar.xul');

$cons->InstallInChrome('widgetFloating.xul');

$cons->InstallInChrome('browser.xul');
