#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'build',
    'buildFlavour',
    'mozBin',
    'mozVersion',
    'platform',
    'productType',
    'sdkDir',
    'unsiloedPythonExe',
);

$cons->KoExt("koinstall --unjarred");
