#!/usr/local/bin/perl
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Komodo code.
# 
# The Initial Developer of the Original Code is ActiveState Software Inc.
# Portions created by ActiveState Software Inc are Copyright (C) 2000-2007
# ActiveState Software Inc. All Rights Reserved.
# 
# Contributor(s):
#   ActiveState Software Inc
# 
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
# 
# ***** END LICENSE BLOCK *****

Import(
    'cons', 
    'mozChromeDir',
    'platform',
    'productType',
    'buildFlavour',
    'unsiloedPythonExe',
    'mozVersion',
);

$cons->InstallInChrome('bindings.less');
$cons->InstallInChrome('colors.less');
$cons->InstallInChrome('chromeless.less');
$cons->InstallInChrome('normalize.less');
$cons->InstallInChrome('prefs.less');
$cons->InstallInChrome('reset.less');
$cons->InstallInChrome('scrollbars.less');
$cons->InstallInChrome('main.less');
$cons->InstallInChrome('global.less');
$cons->InstallInChrome('icons.less');
$cons->InstallInChrome('mixins.less');

$cons->InstallInChrome('components/buttons.less');
$cons->InstallInChrome('components/languages.less');
$cons->InstallInChrome('components/scrolltabs.less');
$cons->InstallInChrome('components/scc.less');

$cons->InstallInChrome('icons/style.less');
$cons->InstallInChrome('icons/variables.less');
$cons->InstallInChrome('icons/fonts/icomoon.eot');
$cons->InstallInChrome('icons/fonts/icomoon.svg');
$cons->InstallInChrome('icons/fonts/icomoon.ttf');
$cons->InstallInChrome('icons/fonts/icomoon.woff');

#$cons->InstallAs("$mozChromeDir/komodo/skin/global/global.css",
#                 "$mozChromeDir/toolkit/skin/classic/global/global.css");