#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'build',
    'mozBin',
    'mozChromeDir',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'unsiloedPythonExe',
    'jarring',
    'mozMajorVersion',
    'mozMinorVersion',
    'buildFlavour',
    'mozExtensionDir',
);

if ($buildFlavour ne "full") {
    $cons->InstallAs("$mozExtensionDir/casper\@ActiveState.com/chrome/content/test/test_test.js", 'test_test.js');
    $cons->InstallAs("$mozExtensionDir/casper\@ActiveState.com/chrome/content/test/test_async.js", 'test_async.js');
    $cons->InstallAs("$mozExtensionDir/casper\@ActiveState.com/chrome/content/test/_event_test_template.js", '_event_test_template.js');
}

